import openpyxl
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side

def style_rows(ws, start_row, end_row):
    thin_border = Border(
        left=Side(style='thin'), right=Side(style='thin'),
        top=Side(style='thin'), bottom=Side(style='thin')
    )
    wrap = Alignment(wrap_text=True, vertical='top')
    for row in range(start_row, end_row + 1):
        for col in range(1, ws.max_column + 1):
            cell = ws.cell(row=row, column=col)
            cell.alignment = wrap
            cell.border = thin_border

def append_to_file(filepath, new_data):
    wb = openpyxl.load_workbook(filepath)
    ws = wb.active
    start_row = ws.max_row + 1
    for row_data in new_data:
        ws.append(row_data)
    style_rows(ws, start_row, ws.max_row)
    wb.save(filepath)
    print(f"  Updated: {filepath} — added {len(new_data)} test cases. Total: {ws.max_row - 1}")

# ============================================================
# 1. CONVERSATION LIST — Expand
# ============================================================
print("\n1. CONVERSATION LIST")
cl_expand = [
    # --- Integration ---
    ["CL_025", "Positive", "Integration: Conversation List with Message List", "User is logged in with conversations",
     "Verify opening conversation navigates to correct message list",
     "1. Click on a conversation.\n2. Verify messages belong to that conversation.",
     "Message list should load messages only for the selected conversation. No cross-conversation data.",
     "High / High"],
    ["CL_026", "", "", "",
     "Verify new message updates conversation list preview and order",
     "1. Send a message in an older conversation.\n2. Observe conversation list.",
     "Conversation should move to top with updated preview message and timestamp.",
     "High / High"],
    ["CL_027", "", "", "",
     "Verify read status syncs between conversation list and message list",
     "1. Open an unread conversation.\n2. Read messages.\n3. Go back to list.",
     "Unread badge should disappear from the conversation in the list.",
     "High / High"],
    ["CL_028", "", "Integration: Conversation List with Notifications", "User is logged in, app in background",
     "Verify notification updates conversation list on app resume",
     "1. Receive messages while app is in background.\n2. Open app.",
     "Conversation list should refresh with new messages reflected in preview and order.",
     "High / High"],

    # --- Regression ---
    ["CL_029", "Positive", "Regression: Conversation List after actions", "User is logged in with conversations",
     "Verify conversation list intact after deleting a conversation",
     "1. Delete a conversation.\n2. Observe remaining conversations.",
     "Remaining conversations should maintain correct order, previews, and timestamps. No data corruption.",
     "High / High"],
    ["CL_030", "", "", "",
     "Verify conversation list intact after blocking a user",
     "1. Block a user.\n2. Observe conversation list.",
     "Blocked user's conversation should be handled per app policy (hidden or marked). Other conversations unaffected.",
     "High / High"],
    ["CL_031", "", "", "",
     "Verify conversation list after app update/restart",
     "1. Close and reopen the app.\n2. Observe conversation list.",
     "All conversations should reload correctly with accurate previews and order.",
     "High / High"],
    ["CL_032", "", "", "",
     "Verify conversation list after logout and re-login",
     "1. Logout.\n2. Login with same account.\n3. Observe conversation list.",
     "All previous conversations should load correctly.",
     "High / High"],

    # --- Security ---
    ["CL_033", "Positive", "Security: Conversation List", "User is logged in",
     "Verify conversation list shows only authorized conversations",
     "1. Login as User A.\n2. Observe conversation list.",
     "Only conversations where User A is a participant should display. No other users' conversations visible.",
     "High / Critical"],
    ["CL_034", "", "", "",
     "Verify conversation preview does not expose sensitive data",
     "1. Observe preview messages in conversation list.",
     "Sensitive content (passwords, tokens) should not be visible in preview. Media messages should show placeholder text.",
     "High / Critical"],
    ["CL_035", "Negative", "Security: Conversation List", "User is not logged in",
     "Verify conversation list not accessible without authentication",
     "1. Try to access conversation list without logging in.",
     "Should redirect to login page. No conversation data should be exposed.",
     "High / Critical"],
    ["CL_036", "", "", "User session expired",
     "Verify conversation list handles expired session",
     "1. Let session expire.\n2. Try to interact with conversation list.",
     "Should prompt re-authentication. No stale data should be accessible.",
     "High / Critical"],

    # --- Edge Cases ---
    ["CL_037", "Positive", "Edge Case: Conversation List", "User is logged in",
     "Verify conversation list with 1000+ conversations",
     "1. Have an account with 1000+ conversations.\n2. Open conversation list.",
     "List should load with pagination/infinite scroll. No performance degradation or crash.",
     "High / High"],
    ["CL_038", "", "", "",
     "Verify conversation with extremely long group name",
     "1. Create a group with a 255-character name.\n2. Observe in conversation list.",
     "Group name should truncate with ellipsis. No layout breaking.",
     "Medium / Medium"],
    ["CL_039", "", "", "",
     "Verify conversation with special characters in name",
     "1. Have a conversation with user/group name containing emojis, unicode, RTL characters.",
     "Name should display correctly without rendering issues.",
     "Medium / Medium"],
    ["CL_040", "", "", "",
     "Verify conversation list with rapid message updates",
     "1. Receive 50+ messages in quick succession across different conversations.",
     "List should update smoothly without flickering, freezing, or incorrect ordering.",
     "High / High"],
    ["CL_041", "", "", "",
     "Verify conversation preview with empty message (media only)",
     "1. Send an image with no caption in a conversation.\n2. Observe preview.",
     "Preview should show placeholder like '📷 Photo' or 'Image' instead of blank.",
     "Medium / Medium"],
    ["CL_042", "Negative", "Edge Case: Conversation List", "User is logged in",
     "Verify conversation list when server returns error",
     "1. Simulate server error (500).\n2. Observe conversation list.",
     "Error message should display with retry option. App should not crash.",
     "High / High"],
    ["CL_043", "", "", "",
     "Verify conversation list with slow network (2G/3G)",
     "1. Throttle network to 2G speed.\n2. Open conversation list.",
     "Loading indicator should show. List should eventually load. No timeout crash.",
     "Medium / High"],

    # --- Boundary Values ---
    ["CL_044", "Positive", "Boundary: Conversation List", "User is logged in",
     "Verify conversation list with exactly 0 conversations",
     "1. Login with new account with no conversations.",
     "Empty state should display correctly with appropriate message.",
     "Medium / Medium"],
    ["CL_045", "", "", "",
     "Verify conversation list with exactly 1 conversation",
     "1. Have exactly 1 conversation.\n2. Open list.",
     "Single conversation should display correctly with all elements.",
     "Medium / Medium"],
    ["CL_046", "", "", "",
     "Verify preview message with 1 character",
     "1. Send a single character message.\n2. Observe preview.",
     "Single character should display correctly in preview.",
     "Low / Low"],
    ["CL_047", "", "", "",
     "Verify preview message with maximum length text",
     "1. Send a very long message (5000+ chars).\n2. Observe preview.",
     "Preview should truncate appropriately with ellipsis.",
     "Medium / Medium"],

    # --- Equivalence Partitioning ---
    ["CL_048", "Positive", "Equivalence Partitioning: Conversation Types", "User is logged in",
     "Verify one-on-one conversation display",
     "1. Observe a one-on-one conversation in list.",
     "Should show user avatar, name, last message preview, time, and unread count.",
     "High / High"],
    ["CL_049", "", "", "",
     "Verify public group conversation display",
     "1. Observe a public group conversation in list.",
     "Should show group avatar, group name, last message with sender prefix, time.",
     "High / High"],
    ["CL_050", "", "", "",
     "Verify private group conversation display",
     "1. Observe a private group conversation in list.",
     "Should show group avatar with lock icon, group name, last message, time.",
     "High / High"],
    ["CL_051", "", "", "",
     "Verify password-protected group conversation display",
     "1. Observe a password-protected group conversation in list.",
     "Should show group avatar, group name, last message, time. Password icon if applicable.",
     "Medium / Medium"],
]

append_to_file('cometchat-test-cases/Conversation_List/Conversation_List_Test_Cases.xlsx', cl_expand)


# ============================================================
# 2. MESSAGE LIST — Expand
# ============================================================
print("\n2. MESSAGE LIST")
ml_expand = [
    # --- Integration ---
    ["ML_064", "Positive", "Integration: Message List with Composer", "User is logged in and chat is open",
     "Verify sent message from composer appears in message list",
     "1. Type a message in composer.\n2. Send.\n3. Observe message list.",
     "Sent message should immediately appear in message list at the bottom with correct content and timestamp.",
     "High / High"],
    ["ML_065", "", "Integration: Message List with Conversation List", "",
     "Verify message list updates reflect in conversation list preview",
     "1. Send a message.\n2. Go back to conversation list.",
     "Conversation preview should show the latest sent message text and updated timestamp.",
     "High / High"],
    ["ML_066", "", "Integration: Message List with User Profile", "",
     "Verify tapping user avatar opens user profile",
     "1. Tap on a user's avatar in message list.",
     "User profile/info panel should open with user details.",
     "Medium / Medium"],
    ["ML_067", "", "Integration: Message List with Real-time Events", "",
     "Verify real-time message delivery from another user",
     "1. User B sends a message to User A.\n2. Observe User A's message list.",
     "Message should appear in real-time without manual refresh.",
     "High / High"],
    ["ML_068", "", "", "",
     "Verify typing indicator in message list",
     "1. User B starts typing.\n2. Observe User A's chat.",
     "Typing indicator (e.g., 'User B is typing...') should appear and disappear when typing stops.",
     "Medium / Medium"],
    ["ML_069", "", "Integration: Message List with Read Receipts", "",
     "Verify read receipts (double tick/blue tick)",
     "1. Send a message.\n2. Receiver reads it.\n3. Observe sender's message.",
     "Message should show read receipt indicator (blue double tick or similar).",
     "High / High"],
    ["ML_070", "", "", "",
     "Verify delivered receipt (single/double tick)",
     "1. Send a message.\n2. Message gets delivered but not read.",
     "Message should show delivered indicator (double grey tick or similar).",
     "High / High"],

    # --- Regression ---
    ["ML_071", "Positive", "Regression: Message List after actions", "User is logged in and chat is open",
     "Verify message list intact after editing a message",
     "1. Edit a message.\n2. Observe entire message list.",
     "Only edited message should change. All other messages should remain intact with correct order.",
     "High / High"],
    ["ML_072", "", "", "",
     "Verify message list intact after deleting a message",
     "1. Delete a message.\n2. Observe message list.",
     "Deleted message should be removed/replaced. All other messages unaffected.",
     "High / High"],
    ["ML_073", "", "", "",
     "Verify message list after switching between conversations",
     "1. Open conversation A.\n2. Switch to conversation B.\n3. Switch back to A.",
     "Conversation A should reload with correct messages. No message mixing between conversations.",
     "High / High"],
    ["ML_074", "", "", "",
     "Verify message list after app backgrounding and resuming",
     "1. Open a chat.\n2. Background the app for 5 minutes.\n3. Resume.",
     "Message list should refresh with any new messages received while backgrounded.",
     "High / High"],

    # --- Security ---
    ["ML_075", "Positive", "Security: Message List", "User is logged in",
     "Verify messages only visible to conversation participants",
     "1. Login as User A.\n2. Open a conversation with User B.",
     "Only messages between A and B should display. No messages from other conversations should leak.",
     "High / Critical"],
    ["ML_076", "", "", "",
     "Verify message content not exposed in URL or logs",
     "1. Send messages.\n2. Check browser URL bar and console logs.",
     "Message content should not appear in URLs, query parameters, or client-side logs.",
     "High / Critical"],
    ["ML_077", "Negative", "Security: Message List", "",
     "Verify XSS prevention in message display",
     "1. Send a message containing '<script>alert(1)</script>'.\n2. Observe in receiver's message list.",
     "Script should NOT execute. HTML should be escaped/sanitized and displayed as plain text.",
     "High / Critical"],
    ["ML_078", "", "", "",
     "Verify SQL injection prevention in messages",
     "1. Send a message containing SQL injection payload (e.g., \"'; DROP TABLE messages;--\").",
     "Message should display as plain text. No database errors or data loss.",
     "High / Critical"],
    ["ML_079", "", "", "",
     "Verify message with malicious URL",
     "1. Send a message with a phishing/malicious URL.\n2. Observe link preview.",
     "Link should be clickable but app should warn about external links or have URL validation.",
     "Medium / High"],

    # --- Edge Cases ---
    ["ML_080", "Positive", "Edge Case: Message List", "User is logged in and chat is open",
     "Verify message list with 10000+ messages in conversation",
     "1. Open a conversation with 10000+ messages.\n2. Scroll through.",
     "Messages should load via pagination. No memory leak, crash, or extreme slowness.",
     "High / High"],
    ["ML_081", "", "", "",
     "Verify message with only whitespace/spaces",
     "1. Send a message with only spaces.\n2. Observe message list.",
     "Message should either be blocked from sending or display as empty bubble.",
     "Medium / Medium"],
    ["ML_082", "", "", "",
     "Verify message with mixed RTL and LTR text",
     "1. Send a message mixing Arabic/Hebrew with English text.",
     "Text should render correctly with proper bidirectional formatting.",
     "Medium / Medium"],
    ["ML_083", "", "", "",
     "Verify message with 50+ emojis",
     "1. Send a message with 50+ emojis.",
     "All emojis should render correctly. No performance issues or layout breaking.",
     "Low / Medium"],
    ["ML_084", "", "", "",
     "Verify simultaneous messages from multiple users in group",
     "1. Have 10 users send messages simultaneously in a group.",
     "All messages should appear in correct chronological order. No duplicates or missing messages.",
     "High / High"],
    ["ML_085", "", "", "",
     "Verify message with extremely long single word (no spaces)",
     "1. Send a message with a 1000-character word with no spaces.",
     "Message bubble should handle word-break/overflow. No horizontal scrolling or layout break.",
     "Medium / Medium"],
    ["ML_086", "Negative", "Edge Case: Message List", "",
     "Verify message list when WebSocket disconnects",
     "1. Simulate WebSocket disconnection during active chat.",
     "App should show reconnecting indicator. Messages should sync once reconnected.",
     "High / High"],
    ["ML_087", "", "", "",
     "Verify message list with corrupted/invalid message data",
     "1. Simulate receiving a message with missing or malformed fields.",
     "App should handle gracefully — skip or show placeholder. No crash.",
     "High / High"],

    # --- Boundary Values ---
    ["ML_088", "Positive", "Boundary: Message List", "User is logged in and chat is open",
     "Verify message with exactly 1 character",
     "1. Send a single character 'a'.",
     "Message should display correctly in a properly sized bubble.",
     "Low / Low"],
    ["ML_089", "", "", "",
     "Verify message with maximum allowed characters",
     "1. Send a message at the maximum character limit (e.g., 65535 chars).",
     "Message should send and display correctly. May need 'Read more' expansion.",
     "Medium / Medium"],
    ["ML_090", "", "", "",
     "Verify message at character limit + 1",
     "1. Try to send a message exceeding the maximum character limit by 1.",
     "Message should be blocked or truncated. Appropriate error/warning should display.",
     "Medium / Medium"],
    ["ML_091", "", "", "",
     "Verify reaction with maximum number of unique reactions",
     "1. Add the maximum number of different reaction emojis to a single message.",
     "All reactions should display. UI should handle overflow (e.g., '+5 more').",
     "Medium / Medium"],
    ["ML_092", "", "", "",
     "Verify message list with exactly 0 messages (new conversation)",
     "1. Open a brand new conversation with no messages.",
     "Empty state should display. Composer should be ready for first message.",
     "Medium / Medium"],

    # --- Equivalence Partitioning ---
    ["ML_093", "Positive", "Equivalence Partitioning: Message Types", "User is logged in and chat is open",
     "Verify short text message (1-50 chars)",
     "1. Send a message with 25 characters.",
     "Message should display in a compact bubble.",
     "High / High"],
    ["ML_094", "", "", "",
     "Verify medium text message (51-500 chars)",
     "1. Send a message with 250 characters.",
     "Message should display in a medium-sized bubble with proper wrapping.",
     "High / High"],
    ["ML_095", "", "", "",
     "Verify long text message (501-5000 chars)",
     "1. Send a message with 2500 characters.",
     "Message should display with 'Read more' or expandable view.",
     "High / High"],
    ["ML_096", "", "", "",
     "Verify very long text message (5000+ chars)",
     "1. Send a message with 10000 characters.",
     "Message should handle gracefully with expansion option. No performance issues.",
     "Medium / Medium"],
    ["ML_097", "", "Equivalence Partitioning: Media Sizes", "",
     "Verify small image (<100KB)",
     "1. Send an image under 100KB.",
     "Image should upload quickly and display as thumbnail.",
     "High / High"],
    ["ML_098", "", "", "",
     "Verify medium image (100KB-5MB)",
     "1. Send an image of 2MB.",
     "Image should upload with progress indicator and display correctly.",
     "High / High"],
    ["ML_099", "", "", "",
     "Verify large image (5MB-25MB)",
     "1. Send an image of 15MB.",
     "Image should upload with progress bar. May take longer. Should complete successfully.",
     "High / High"],
    ["ML_100", "Negative", "", "",
     "Verify oversized image (>25MB or above limit)",
     "1. Try to send an image exceeding the file size limit.",
     "Error message should display. File should not upload.",
     "High / High"],
]

append_to_file('cometchat-test-cases/Message_List/Message_List_Test_Cases.xlsx', ml_expand)


# ============================================================
# 3. ADVANCED SEARCH — Expand
# ============================================================
print("\n3. ADVANCED SEARCH")
as_expand = [
    # --- Integration ---
    ["AS_036", "Positive", "Integration: Advanced Search with Message List", "User is logged in",
     "Verify search result navigates to correct message in conversation",
     "1. Search for a keyword.\n2. Tap on a result.\n3. Verify the message in context.",
     "Should navigate to the exact conversation and scroll to the matching message. Message should be highlighted.",
     "High / High"],
    ["AS_037", "", "Integration: Advanced Search with Conversation List", "",
     "Verify search results reflect recently sent messages",
     "1. Send a new message with unique keyword.\n2. Immediately search for that keyword.",
     "Newly sent message should appear in search results.",
     "High / High"],

    # --- Regression ---
    ["AS_038", "Positive", "Regression: Advanced Search", "User is logged in",
     "Verify search results after deleting a message",
     "1. Search for a keyword.\n2. Delete a message containing that keyword.\n3. Search again.",
     "Deleted message should no longer appear in search results.",
     "High / High"],
    ["AS_039", "", "", "",
     "Verify search results after editing a message",
     "1. Search for 'hello'.\n2. Edit a message from 'hello' to 'goodbye'.\n3. Search 'hello' again.",
     "'hello' result should disappear. Searching 'goodbye' should show the edited message.",
     "High / High"],
    ["AS_040", "", "", "",
     "Verify search works after app restart",
     "1. Close and reopen app.\n2. Perform advanced search.",
     "Search should work correctly with all historical data accessible.",
     "Medium / Medium"],

    # --- Security ---
    ["AS_041", "Negative", "Security: Advanced Search", "User is logged in",
     "Verify search does not return messages from other users' private conversations",
     "1. Search for a common keyword.\n2. Observe results.",
     "Results should only include messages from conversations the user is a participant of.",
     "High / Critical"],
    ["AS_042", "", "", "",
     "Verify XSS prevention in search input",
     "1. Type '<script>alert(1)</script>' in search field.",
     "Script should not execute. Input should be sanitized.",
     "High / Critical"],
    ["AS_043", "", "", "",
     "Verify search input sanitization against injection",
     "1. Type SQL/NoSQL injection payloads in search field.",
     "Search should handle gracefully. No server errors or data exposure.",
     "High / Critical"],

    # --- Edge Cases ---
    ["AS_044", "Positive", "Edge Case: Advanced Search", "User is logged in",
     "Verify search with single character",
     "1. Search for 'a'.",
     "Should return results or show minimum character requirement message.",
     "Medium / Medium"],
    ["AS_045", "", "", "",
     "Verify search with 500+ character query",
     "1. Paste a very long string (500+ chars) in search.",
     "Search should handle gracefully — truncate input or show max length warning.",
     "Low / Medium"],
    ["AS_046", "", "", "",
     "Verify search with only emojis",
     "1. Search for '😀🎉'.",
     "Should return messages containing those emojis or show no results.",
     "Low / Low"],
    ["AS_047", "", "", "",
     "Verify search with unicode/multilingual text",
     "1. Search for text in Chinese/Arabic/Hindi/Japanese.",
     "Should return matching messages in those languages correctly.",
     "Medium / Medium"],
    ["AS_048", "Negative", "", "",
     "Verify search during high server load",
     "1. Perform search during peak usage.",
     "Search should complete (may be slower) or show timeout message. No crash.",
     "Medium / High"],
    ["AS_049", "", "", "",
     "Verify rapid consecutive searches",
     "1. Type and search rapidly, changing keywords every second.",
     "App should debounce requests. Only latest search results should display. No race conditions.",
     "Medium / High"],

    # --- Boundary Values ---
    ["AS_050", "Positive", "Boundary: Advanced Search", "User is logged in",
     "Verify search returning exactly 0 results",
     "1. Search for a unique string that doesn't exist.",
     "Empty state should display with 'No results found' message.",
     "Medium / Medium"],
    ["AS_051", "", "", "",
     "Verify search returning exactly 1 result",
     "1. Search for a unique keyword that exists in only one message.",
     "Single result should display correctly with all details.",
     "Medium / Medium"],
    ["AS_052", "", "", "",
     "Verify search returning 1000+ results",
     "1. Search for a very common word like 'the' or 'hi'.",
     "Results should load with pagination/infinite scroll. Performance should be acceptable.",
     "Medium / Medium"],

    # --- Equivalence Partitioning ---
    ["AS_053", "Positive", "Equivalence Partitioning: Search Query Types", "User is logged in",
     "Verify search with alphabetic characters only",
     "1. Search for 'hello'.",
     "Should return matching text messages.",
     "High / High"],
    ["AS_054", "", "", "",
     "Verify search with numeric characters only",
     "1. Search for '12345'.",
     "Should return messages containing that number.",
     "Medium / Medium"],
    ["AS_055", "", "", "",
     "Verify search with alphanumeric mix",
     "1. Search for 'test123'.",
     "Should return messages containing 'test123'.",
     "Medium / Medium"],
    ["AS_056", "", "", "",
     "Verify search with special characters",
     "1. Search for '@#$%'.",
     "Should handle gracefully — return matching results or empty state.",
     "Low / Medium"],
]

append_to_file('cometchat-test-cases/Advanced_Search/Advanced_Search_Test_Cases.xlsx', as_expand)


# ============================================================
# 4. CONVERSATION SEARCH — Expand
# ============================================================
print("\n4. CONVERSATION SEARCH")
cs_expand = [
    # --- Integration ---
    ["CS_038", "Positive", "Integration: Conversation Search with Chat", "User is logged in",
     "Verify search result opens correct conversation",
     "1. Search for a contact name.\n2. Tap on result.",
     "Should open the correct conversation with full message history.",
     "High / High"],
    ["CS_039", "", "", "",
     "Verify search reflects real-time new conversations",
     "1. Receive a message from a new user.\n2. Search for that user's name.",
     "New conversation should appear in search results immediately.",
     "High / High"],

    # --- Regression ---
    ["CS_040", "Positive", "Regression: Conversation Search", "User is logged in",
     "Verify search works after deleting a conversation",
     "1. Delete a conversation.\n2. Search for that contact/group.",
     "Deleted conversation should not appear in search results.",
     "High / High"],
    ["CS_041", "", "", "",
     "Verify search works after leaving a group",
     "1. Leave a group.\n2. Search for that group name.",
     "Left group should not appear in search results (or appear as 'Left').",
     "High / High"],
    ["CS_042", "", "", "",
     "Verify search after clearing chat history",
     "1. Clear chat history of a conversation.\n2. Search for messages from that chat.",
     "Cleared messages should not appear. Conversation may still appear but with no message matches.",
     "Medium / Medium"],

    # --- Security ---
    ["CS_043", "Negative", "Security: Conversation Search", "User is logged in",
     "Verify search does not expose other users' conversations",
     "1. Search for another user's private group name that you're not part of.",
     "No results should appear for conversations user is not a participant of.",
     "High / Critical"],
    ["CS_044", "", "", "",
     "Verify XSS prevention in search input",
     "1. Type '<img src=x onerror=alert(1)>' in search bar.",
     "Input should be sanitized. No script execution.",
     "High / Critical"],
    ["CS_045", "", "", "",
     "Verify search input length limit enforced",
     "1. Try to paste 10000+ characters in search bar.",
     "Input should be truncated or rejected. No buffer overflow or crash.",
     "Medium / High"],

    # --- Edge Cases ---
    ["CS_046", "Positive", "Edge Case: Conversation Search", "User is logged in",
     "Verify search with leading/trailing spaces",
     "1. Search for '  John  ' (with spaces).",
     "Should trim spaces and return results for 'John'.",
     "Low / Medium"],
    ["CS_047", "", "", "",
     "Verify search with only spaces",
     "1. Type only spaces in search bar.",
     "Should show all conversations or ignore the search. No error.",
     "Low / Low"],
    ["CS_048", "", "", "",
     "Verify search with emoji in contact/group name",
     "1. Have a group named '🎮 Gamers'.\n2. Search for '🎮' or 'Gamers'.",
     "Group should appear in results for both emoji and text search.",
     "Medium / Medium"],
    ["CS_049", "Negative", "", "",
     "Verify search behavior during network fluctuation",
     "1. Start searching while network is intermittent.",
     "Should show loading state and handle timeouts gracefully. Retry on reconnect.",
     "Medium / High"],

    # --- Boundary Values ---
    ["CS_050", "Positive", "Boundary: Conversation Search", "User is logged in",
     "Verify search with minimum 1 character",
     "1. Type a single character in search.",
     "Should filter conversations or show minimum character requirement.",
     "Medium / Medium"],
    ["CS_051", "", "", "",
     "Verify search with maximum input length",
     "1. Type the maximum allowed characters in search.",
     "Search should execute correctly at the boundary.",
     "Low / Low"],

    # --- Equivalence Partitioning ---
    ["CS_052", "Positive", "Equivalence Partitioning: Search Targets", "User is logged in",
     "Verify search matches user first name",
     "1. Search for a user's first name.",
     "Conversations with matching first name should appear.",
     "High / High"],
    ["CS_053", "", "", "",
     "Verify search matches user last name",
     "1. Search for a user's last name.",
     "Conversations with matching last name should appear.",
     "High / High"],
    ["CS_054", "", "", "",
     "Verify search matches group name",
     "1. Search for a group name.",
     "Matching group conversations should appear.",
     "High / High"],
    ["CS_055", "", "", "",
     "Verify search matches message content",
     "1. Search for a keyword from a message.",
     "Conversations containing that keyword in messages should appear.",
     "High / High"],
]

append_to_file('cometchat-test-cases/Conversation_Search/Conversation_Search_Test_Cases.xlsx', cs_expand)


# ============================================================
# 5. COMPOSER — Expand
# ============================================================
print("\n5. COMPOSER")
comp_expand = [
    # --- Integration ---
    ["COMP_027", "Positive", "Integration: Composer with Message List", "User is logged in and chat is open",
     "Verify sent message appears in message list immediately",
     "1. Type and send a message.\n2. Observe message list.",
     "Message should appear at the bottom of message list instantly with 'sending' then 'sent' status.",
     "High / High"],
    ["COMP_028", "", "Integration: Composer with Typing Indicator", "",
     "Verify typing in composer triggers typing indicator for receiver",
     "1. Start typing in composer.\n2. Check receiver's chat.",
     "Receiver should see 'User is typing...' indicator.",
     "Medium / Medium"],
    ["COMP_029", "", "Integration: Composer with Reply", "",
     "Verify composer shows reply preview when replying",
     "1. Select 'Reply' on a message.\n2. Observe composer.",
     "Reply preview should appear above input with original message snippet and close button.",
     "High / High"],
    ["COMP_030", "", "Integration: Composer with Edit", "",
     "Verify composer populates message text when editing",
     "1. Select 'Edit' on own message.\n2. Observe composer.",
     "Composer should populate with the original message text, ready for editing.",
     "High / High"],

    # --- Regression ---
    ["COMP_031", "Positive", "Regression: Composer", "User is logged in and chat is open",
     "Verify composer clears after sending message",
     "1. Type and send a message.",
     "Composer input should clear completely after message is sent.",
     "High / High"],
    ["COMP_032", "", "", "",
     "Verify composer state after switching conversations",
     "1. Type a draft in conversation A.\n2. Switch to conversation B.\n3. Switch back to A.",
     "Draft text should either persist or clear based on app behavior. No cross-conversation text leaking.",
     "High / High"],
    ["COMP_033", "", "", "",
     "Verify composer after canceling reply/edit",
     "1. Start a reply.\n2. Cancel it.\n3. Type a new message.",
     "Composer should return to normal state. New message should send as regular message, not reply.",
     "High / High"],

    # --- Security ---
    ["COMP_034", "Negative", "Security: Composer", "User is logged in and chat is open",
     "Verify HTML/script injection via composer",
     "1. Type '<script>alert(document.cookie)</script>' in composer.\n2. Send.",
     "Message should be sent as plain text. No script execution on receiver's end.",
     "High / Critical"],
    ["COMP_035", "", "", "",
     "Verify file upload validates file type",
     "1. Try to attach a .exe or .bat file via composer.",
     "Dangerous file types should be blocked with appropriate error message.",
     "High / Critical"],
    ["COMP_036", "", "", "",
     "Verify attachment does not allow path traversal",
     "1. Try to upload a file with path traversal in filename (e.g., '../../etc/passwd').",
     "File should be rejected or filename sanitized. No server-side path traversal.",
     "High / Critical"],

    # --- Edge Cases ---
    ["COMP_037", "Positive", "Edge Case: Composer", "User is logged in and chat is open",
     "Verify composer with rapid send button clicks",
     "1. Type a message.\n2. Click send button 10 times rapidly.",
     "Message should be sent only once. No duplicate messages.",
     "High / High"],
    ["COMP_038", "", "", "",
     "Verify paste large text from clipboard",
     "1. Copy 50000 characters.\n2. Paste into composer.",
     "Text should paste (may be truncated at limit). No crash or freeze.",
     "Medium / Medium"],
    ["COMP_039", "", "", "",
     "Verify composer with multiple attachments simultaneously",
     "1. Select 5+ files at once for attachment.",
     "All files should queue for upload or show max attachment limit message.",
     "Medium / Medium"],
    ["COMP_040", "", "", "",
     "Verify emoji picker with search",
     "1. Open emoji picker.\n2. Search for 'smile'.",
     "Matching emojis should filter and display. Selecting one should insert into composer.",
     "Medium / Medium"],
    ["COMP_041", "", "", "",
     "Verify sticker picker categories",
     "1. Open sticker picker.\n2. Browse categories.",
     "Sticker categories should load. Selecting a sticker should send it.",
     "Medium / Medium"],
    ["COMP_042", "Negative", "Edge Case: Composer", "",
     "Verify composer when keyboard is dismissed mid-typing",
     "1. Start typing.\n2. Dismiss keyboard (mobile).\n3. Reopen keyboard.",
     "Typed text should persist. No data loss.",
     "Medium / Medium"],

    # --- Boundary Values ---
    ["COMP_043", "Positive", "Boundary: Composer", "User is logged in and chat is open",
     "Verify sending message at exactly max character limit",
     "1. Type exactly the maximum allowed characters.\n2. Send.",
     "Message should send successfully.",
     "Medium / Medium"],
    ["COMP_044", "Negative", "", "",
     "Verify sending message at max character limit + 1",
     "1. Try to type one character beyond the max limit.",
     "Input should be blocked or warning should display.",
     "Medium / Medium"],
    ["COMP_045", "Positive", "", "",
     "Verify attachment at exactly max file size",
     "1. Attach a file at exactly the maximum allowed size.\n2. Send.",
     "File should upload and send successfully.",
     "Medium / Medium"],
    ["COMP_046", "Negative", "", "",
     "Verify attachment at max file size + 1 byte",
     "1. Attach a file 1 byte over the maximum size.",
     "Error message should display. File should not upload.",
     "Medium / Medium"],

    # --- Equivalence Partitioning ---
    ["COMP_047", "Positive", "Equivalence Partitioning: Input Types", "User is logged in and chat is open",
     "Verify sending plain text message",
     "1. Type plain English text.\n2. Send.",
     "Message should send and display correctly.",
     "High / High"],
    ["COMP_048", "", "", "",
     "Verify sending message with only emojis",
     "1. Select emojis only from picker.\n2. Send.",
     "Emoji message should send and display in larger size.",
     "Medium / Medium"],
    ["COMP_049", "", "", "",
     "Verify sending message with mixed text and emojis",
     "1. Type text with emojis interspersed.\n2. Send.",
     "Message should display with inline emojis at normal text size.",
     "Medium / Medium"],
    ["COMP_050", "", "", "",
     "Verify sending message with only numbers",
     "1. Type '1234567890'.\n2. Send.",
     "Numeric message should send and display correctly. Should not be interpreted as phone number unless intended.",
     "Low / Low"],
    ["COMP_051", "", "", "",
     "Verify sending message with URLs",
     "1. Type a message containing 'https://example.com'.\n2. Send.",
     "URL should be clickable/tappable in the sent message. Link preview may generate.",
     "High / High"],
]

append_to_file('cometchat-test-cases/Composer/Composer_Test_Cases.xlsx', comp_expand)


# ============================================================
# 6. SEND MESSAGE — Expand
# ============================================================
print("\n6. SEND MESSAGE")
msg_expand = [
    # --- Integration ---
    ["MSG_109", "Positive", "Integration: Send Message with Delivery", "User is logged in and chat is open",
     "Verify sent message shows sent/delivered/read status progression",
     "1. Send a message.\n2. Observe status indicators over time.",
     "Message should progress: sending → sent (single tick) → delivered (double tick) → read (blue tick).",
     "High / High"],
    ["MSG_110", "", "Integration: Send Message with Push Notification", "",
     "Verify sent message triggers push notification for receiver",
     "1. Send a message to User B (app in background).",
     "User B should receive a push notification with sender name and message preview.",
     "High / High"],
    ["MSG_111", "", "Integration: Send Message with Conversation List", "",
     "Verify sent message updates conversation list for both sender and receiver",
     "1. Send a message.\n2. Check conversation list on both devices.",
     "Both sender and receiver conversation lists should update with latest message preview.",
     "High / High"],

    # --- Regression ---
    ["MSG_112", "Positive", "Regression: Send Message", "User is logged in and chat is open",
     "Verify message sending works after failed attempt",
     "1. Send a message during network error (fails).\n2. Restore network.\n3. Retry sending.",
     "Message should send successfully on retry. No duplicate messages.",
     "High / High"],
    ["MSG_113", "", "", "",
     "Verify message order preserved after rapid sending",
     "1. Send 10 messages rapidly one after another.",
     "All 10 messages should appear in the exact order they were sent.",
     "High / High"],
    ["MSG_114", "", "", "",
     "Verify media message sending after app crash recovery",
     "1. Start uploading a large file.\n2. Force close app.\n3. Reopen.",
     "Upload should either resume or show failed state with retry option.",
     "Medium / High"],

    # --- Security ---
    ["MSG_115", "Negative", "Security: Send Message", "User is logged in and chat is open",
     "Verify message cannot be sent to unauthorized conversation",
     "1. Try to send a message to a group you've been removed from.",
     "Message should fail with appropriate error. No message delivered.",
     "High / Critical"],
    ["MSG_116", "", "", "",
     "Verify file upload scans for malware (if applicable)",
     "1. Upload a file flagged as potentially malicious.",
     "File should be rejected or quarantined based on security policy.",
     "High / Critical"],
    ["MSG_117", "", "", "",
     "Verify message encryption in transit",
     "1. Send a message.\n2. Inspect network traffic.",
     "Message content should be encrypted (HTTPS/WSS). Not visible in plain text.",
     "High / Critical"],
    ["MSG_118", "", "", "",
     "Verify spoofed sender ID prevention",
     "1. Try to send a message with a manipulated sender ID via API.",
     "Server should reject the message. Sender ID should be validated server-side.",
     "High / Critical"],

    # --- Edge Cases ---
    ["MSG_119", "Positive", "Edge Case: Send Message", "User is logged in and chat is open",
     "Verify sending message while receiver is typing",
     "1. Both users type simultaneously.\n2. Both send at the same time.",
     "Both messages should appear in correct order. No message loss.",
     "Medium / Medium"],
    ["MSG_120", "", "", "",
     "Verify sending message to a user who blocked you",
     "1. Send a message to a user who has blocked you.",
     "Message should fail or appear sent but not delivered. Appropriate handling per app policy.",
     "High / High"],
    ["MSG_121", "", "", "",
     "Verify sending message immediately after joining a group",
     "1. Join a new group.\n2. Immediately send a message.",
     "Message should send successfully. Should appear for all group members.",
     "Medium / Medium"],
    ["MSG_122", "", "", "",
     "Verify sending multiple media types in sequence",
     "1. Send an image.\n2. Immediately send a video.\n3. Send a document.",
     "All three should upload and appear in correct order. No upload conflicts.",
     "High / High"],
    ["MSG_123", "Negative", "Edge Case: Send Message", "",
     "Verify sending message with zero-width characters",
     "1. Send a message containing only zero-width unicode characters.",
     "Message should be blocked or displayed as empty. No invisible messages.",
     "Medium / High"],
    ["MSG_124", "", "", "",
     "Verify sending corrupted media file",
     "1. Rename a .txt file to .jpg.\n2. Try to send as image.",
     "App should detect invalid file and show error. Should not crash.",
     "Medium / High"],

    # --- Boundary Values ---
    ["MSG_125", "Positive", "Boundary: Send Message", "User is logged in and chat is open",
     "Verify sending text message with exactly 1 character",
     "1. Send 'a'.",
     "Single character message should send and display correctly.",
     "Low / Low"],
    ["MSG_126", "", "", "",
     "Verify sending text at max character limit",
     "1. Send a message at exactly the maximum character limit.",
     "Message should send successfully.",
     "Medium / Medium"],
    ["MSG_127", "Negative", "", "",
     "Verify sending text exceeding max character limit",
     "1. Try to send a message exceeding the max limit.",
     "Should be blocked at input or rejected by server with error.",
     "Medium / Medium"],
    ["MSG_128", "Positive", "", "",
     "Verify sending media at minimum file size (1 byte)",
     "1. Send a 1-byte file.",
     "File should either send or be rejected as too small. No crash.",
     "Low / Low"],
    ["MSG_129", "", "", "",
     "Verify sending media at exactly max file size",
     "1. Send a file at exactly the maximum allowed size.",
     "File should upload and send successfully.",
     "Medium / Medium"],

    # --- Equivalence Partitioning ---
    ["MSG_130", "Positive", "Equivalence Partitioning: Message Destinations", "User is logged in",
     "Verify sending message in one-on-one chat",
     "1. Open a one-on-one conversation.\n2. Send a text message.",
     "Message should deliver to the single recipient.",
     "High / High"],
    ["MSG_131", "", "", "",
     "Verify sending message in small group (2-10 members)",
     "1. Open a group with 5 members.\n2. Send a message.",
     "Message should deliver to all group members.",
     "High / High"],
    ["MSG_132", "", "", "",
     "Verify sending message in large group (100+ members)",
     "1. Open a group with 100+ members.\n2. Send a message.",
     "Message should deliver to all members. May have slight delay but should complete.",
     "High / High"],
    ["MSG_133", "", "Equivalence Partitioning: Image Formats", "User is logged in and chat is open",
     "Verify sending JPEG image",
     "1. Send a .jpg image.",
     "Image should upload and display correctly.",
     "High / High"],
    ["MSG_134", "", "", "",
     "Verify sending PNG image",
     "1. Send a .png image.",
     "Image should upload and display correctly with transparency if applicable.",
     "High / High"],
    ["MSG_135", "", "", "",
     "Verify sending GIF image",
     "1. Send a .gif image.",
     "GIF should upload and animate in chat.",
     "Medium / Medium"],
    ["MSG_136", "", "", "",
     "Verify sending WebP image",
     "1. Send a .webp image.",
     "Image should upload and display correctly.",
     "Medium / Medium"],
    ["MSG_137", "", "", "",
     "Verify sending SVG image",
     "1. Send a .svg file.",
     "Should either render or be treated as document. No XSS via SVG.",
     "Medium / High"],
    ["MSG_138", "", "Equivalence Partitioning: Video Formats", "",
     "Verify sending MP4 video",
     "1. Send a .mp4 video.",
     "Video should upload with thumbnail and be playable.",
     "High / High"],
    ["MSG_139", "", "", "",
     "Verify sending MOV video",
     "1. Send a .mov video.",
     "Video should upload and be playable.",
     "Medium / Medium"],
    ["MSG_140", "", "Equivalence Partitioning: Document Formats", "",
     "Verify sending PDF document",
     "1. Send a .pdf file.",
     "PDF should upload with file icon and be downloadable/viewable.",
     "High / High"],
    ["MSG_141", "", "", "",
     "Verify sending DOCX document",
     "1. Send a .docx file.",
     "Document should upload with Word icon and be downloadable.",
     "Medium / Medium"],
    ["MSG_142", "", "", "",
     "Verify sending XLSX spreadsheet",
     "1. Send a .xlsx file.",
     "Spreadsheet should upload with Excel icon and be downloadable.",
     "Medium / Medium"],
]

append_to_file('cometchat-test-cases/Send_Message/Send_Message_Test_Cases.xlsx', msg_expand)


# ============================================================
# 7. SEND THREADED MESSAGE — Expand
# ============================================================
print("\n7. SEND THREADED MESSAGE")
stm_expand = [
    # --- Integration ---
    ["STM_039", "Positive", "Integration: Thread with Message List", "User is logged in and chat is open",
     "Verify thread reply count updates in main message list",
     "1. Reply in a thread.\n2. Close thread.\n3. Observe parent message in main chat.",
     "Parent message should show updated reply count. Clicking count should reopen thread.",
     "High / High"],
    ["STM_040", "", "Integration: Thread with Notifications", "",
     "Verify thread reply triggers notification for thread participants",
     "1. User A replies in a thread.\n2. Check User B's notifications (who also replied in thread).",
     "User B should receive notification for the new thread reply.",
     "High / High"],
    ["STM_041", "", "Integration: Thread with Conversation List", "",
     "Verify thread reply updates conversation list preview",
     "1. Reply in a thread.\n2. Check conversation list.",
     "Conversation preview should update to reflect the thread activity.",
     "Medium / Medium"],

    # --- Regression ---
    ["STM_042", "Positive", "Regression: Threaded Message", "User is logged in and thread is open",
     "Verify thread intact after editing parent message",
     "1. Edit the parent message of a thread.\n2. Open thread.",
     "Thread should remain intact. Parent message should show edited content. All replies preserved.",
     "High / High"],
    ["STM_043", "", "", "",
     "Verify thread behavior after deleting parent message",
     "1. Delete the parent message that has a thread.",
     "Thread should be handled per policy — either deleted with parent or preserved with 'deleted message' parent.",
     "High / High"],
    ["STM_044", "", "", "",
     "Verify thread after app restart",
     "1. Open a thread.\n2. Close and reopen app.\n3. Navigate back to thread.",
     "Thread should load with all previous replies intact.",
     "Medium / Medium"],

    # --- Security ---
    ["STM_045", "Negative", "Security: Threaded Message", "User is logged in",
     "Verify thread messages only visible to conversation participants",
     "1. Login as a non-participant.\n2. Try to access thread messages.",
     "Thread messages should not be accessible to non-participants of the conversation.",
     "High / Critical"],
    ["STM_046", "", "", "",
     "Verify XSS prevention in thread messages",
     "1. Send '<img src=x onerror=alert(1)>' in a thread reply.",
     "HTML should be escaped. No script execution.",
     "High / Critical"],
    ["STM_047", "", "", "",
     "Verify thread message cannot be sent after being removed from group",
     "1. Get removed from a group.\n2. Try to send a thread reply in that group.",
     "Message should fail with appropriate error.",
     "High / Critical"],

    # --- Edge Cases ---
    ["STM_048", "Positive", "Edge Case: Threaded Message", "User is logged in and thread is open",
     "Verify thread with 500+ replies",
     "1. Open a thread with 500+ replies.\n2. Scroll through.",
     "All replies should load via pagination. No performance issues.",
     "Medium / High"],
    ["STM_049", "", "", "",
     "Verify nested thread behavior (reply to a thread reply)",
     "1. Try to reply to a specific message within a thread.",
     "Should either allow nested reply or keep flat thread structure per design.",
     "Medium / Medium"],
    ["STM_050", "", "", "",
     "Verify thread with mixed media types",
     "1. Send text, image, video, audio, and document in the same thread.",
     "All message types should display correctly within the thread.",
     "High / High"],
    ["STM_051", "Negative", "", "",
     "Verify thread reply during network interruption",
     "1. Start sending a thread reply.\n2. Disconnect network mid-send.",
     "Message should show failed state with retry option. No partial/corrupted messages.",
     "High / High"],

    # --- Boundary Values ---
    ["STM_052", "Positive", "Boundary: Threaded Message", "User is logged in and thread is open",
     "Verify thread with exactly 1 reply",
     "1. Reply once in a thread.\n2. Observe thread and parent message.",
     "Thread should show 1 reply. Parent message should show '1 Reply'.",
     "Medium / Medium"],
    ["STM_053", "", "", "",
     "Verify thread reply with exactly 1 character",
     "1. Send 'a' as a thread reply.",
     "Single character reply should display correctly in thread.",
     "Low / Low"],
    ["STM_054", "", "", "",
     "Verify thread reply at max character limit",
     "1. Send a thread reply at exactly the maximum character limit.",
     "Reply should send successfully.",
     "Medium / Medium"],

    # --- Equivalence Partitioning ---
    ["STM_055", "Positive", "Equivalence Partitioning: Thread Contexts", "User is logged in",
     "Verify thread on a text message",
     "1. Start a thread on a text message.\n2. Reply.",
     "Thread should work correctly with text parent message.",
     "High / High"],
    ["STM_056", "", "", "",
     "Verify thread on an image message",
     "1. Start a thread on an image message.\n2. Reply.",
     "Thread should work correctly with image as parent. Image should display in thread header.",
     "High / High"],
    ["STM_057", "", "", "",
     "Verify thread on a video message",
     "1. Start a thread on a video message.\n2. Reply.",
     "Thread should work correctly with video as parent.",
     "Medium / Medium"],
    ["STM_058", "", "", "",
     "Verify thread on a document message",
     "1. Start a thread on a document message.\n2. Reply.",
     "Thread should work correctly with document as parent.",
     "Medium / Medium"],
]

append_to_file('cometchat-test-cases/Send_Threaded_Message/Send_Threaded_Message_Test_Cases.xlsx', stm_expand)


# ============================================================
# 8. GROUP ACTIONS — Expand
# ============================================================
print("\n8. GROUP ACTIONS")
ga_expand = [
    # --- Integration ---
    ["GA_055", "Positive", "Integration: Group Actions with Message List", "User is logged in and group is open",
     "Verify adding member shows system message in chat",
     "1. Add a new member to the group.\n2. Observe message list.",
     "System message 'User X was added' should appear in the group chat.",
     "High / High"],
    ["GA_056", "", "", "",
     "Verify kicking member shows system message in chat",
     "1. Kick a member from the group.\n2. Observe message list.",
     "System message 'User X was removed' should appear in the group chat.",
     "High / High"],
    ["GA_057", "", "Integration: Group Actions with Conversation List", "",
     "Verify leaving group removes it from conversation list",
     "1. Leave a group.\n2. Check conversation list.",
     "Group should be removed from conversation list (or marked as 'Left').",
     "High / High"],
    ["GA_058", "", "Integration: Group Actions with Notifications", "",
     "Verify group action triggers notification for affected members",
     "1. Admin changes a member's scope.\n2. Check affected member's notifications.",
     "Affected member should receive notification about scope change.",
     "Medium / Medium"],

    # --- Regression ---
    ["GA_059", "Positive", "Regression: Group Actions", "User is logged in and is group admin",
     "Verify group actions work after adding and removing same member",
     "1. Add User X.\n2. Remove User X.\n3. Add User X again.",
     "All actions should complete successfully. User X should be a member again.",
     "High / High"],
    ["GA_060", "", "", "",
     "Verify group actions after scope change",
     "1. Change User X from member to admin.\n2. Perform admin actions as User X.",
     "User X should have full admin capabilities after scope change.",
     "High / High"],
    ["GA_061", "", "", "",
     "Verify member list accurate after multiple actions",
     "1. Add 3 members, remove 1, ban 1.\n2. View member list.",
     "Member list should accurately reflect all changes. Counts should be correct.",
     "High / High"],

    # --- Security ---
    ["GA_062", "Negative", "Security: Group Actions", "User is logged in as regular member",
     "Verify non-admin cannot add members",
     "1. Login as regular group member.\n2. Try to add a new member.",
     "Add member option should not be available or action should be rejected.",
     "High / Critical"],
    ["GA_063", "", "", "",
     "Verify non-admin cannot kick members",
     "1. Login as regular group member.\n2. Try to kick another member.",
     "Kick option should not be available or action should be rejected.",
     "High / Critical"],
    ["GA_064", "", "", "",
     "Verify non-admin cannot ban members",
     "1. Login as regular group member.\n2. Try to ban another member.",
     "Ban option should not be available or action should be rejected.",
     "High / Critical"],
    ["GA_065", "", "", "",
     "Verify non-admin cannot change member scope",
     "1. Login as regular group member.\n2. Try to change another member's scope.",
     "Change scope option should not be available or action should be rejected.",
     "High / Critical"],
    ["GA_066", "", "", "User is logged in as group admin",
     "Verify admin cannot kick/ban the group owner",
     "1. As admin, try to kick or ban the group owner.",
     "Action should be blocked. Owner cannot be kicked or banned by admin.",
     "High / Critical"],
    ["GA_067", "", "", "User is not a group member",
     "Verify non-member cannot access group actions",
     "1. Try to access group actions for a group you're not a member of.",
     "Group actions should not be accessible. Appropriate error should display.",
     "High / Critical"],

    # --- Edge Cases ---
    ["GA_068", "Positive", "Edge Case: Group Actions", "User is logged in and is group admin",
     "Verify adding member to group at max member limit",
     "1. Fill group to maximum member limit.\n2. Try to add one more member.",
     "Should show error that group is full. Member should not be added.",
     "High / High"],
    ["GA_069", "", "", "",
     "Verify banning all members except owner",
     "1. Ban all members one by one (except owner).",
     "All members should be banned. Group should still function with owner only.",
     "Medium / Medium"],
    ["GA_070", "", "", "",
     "Verify unbanning a previously banned member",
     "1. Ban a member.\n2. Go to banned members list.\n3. Unban the member.",
     "Member should be unbanned and able to rejoin the group.",
     "High / High"],
    ["GA_071", "", "", "",
     "Verify group actions with 500+ members",
     "1. Open group actions for a group with 500+ members.\n2. View member list.",
     "Member list should load with pagination. Search should work. No performance issues.",
     "Medium / High"],
    ["GA_072", "Negative", "Edge Case: Group Actions", "",
     "Verify simultaneous admin actions on same member",
     "1. Two admins try to kick the same member at the same time.",
     "One action should succeed, the other should fail gracefully. No data corruption.",
     "Medium / High"],

    # --- Boundary Values ---
    ["GA_073", "Positive", "Boundary: Group Actions", "User is logged in and is group admin",
     "Verify group with exactly 2 members (minimum for group)",
     "1. Have a group with exactly 2 members.\n2. Perform group actions.",
     "All applicable actions should work. Leaving should handle last-member scenario.",
     "Medium / Medium"],
    ["GA_074", "", "", "",
     "Verify group with maximum allowed members",
     "1. Fill group to max capacity.\n2. Verify all actions work.",
     "All group actions should function correctly at max capacity.",
     "Medium / Medium"],
    ["GA_075", "", "", "",
     "Verify banned members list with 0 banned members",
     "1. Open banned members list when no one is banned.",
     "Empty state should display with appropriate message.",
     "Low / Low"],

    # --- Equivalence Partitioning ---
    ["GA_076", "Positive", "Equivalence Partitioning: Member Scopes", "User is logged in and is group owner",
     "Verify actions available for Owner scope",
     "1. Login as group owner.\n2. Observe available group actions.",
     "Owner should have all actions: add, kick, ban, change scope, delete group.",
     "High / High"],
    ["GA_077", "", "", "",
     "Verify actions available for Admin scope",
     "1. Login as group admin.\n2. Observe available group actions.",
     "Admin should have: add, kick (members only), ban (members only), change scope (members only).",
     "High / High"],
    ["GA_078", "", "", "",
     "Verify actions available for Moderator scope",
     "1. Login as group moderator.\n2. Observe available group actions.",
     "Moderator should have limited actions per role definition.",
     "High / High"],
    ["GA_079", "", "", "",
     "Verify actions available for Member scope",
     "1. Login as regular group member.\n2. Observe available group actions.",
     "Member should only have: leave group, view members. No admin actions.",
     "High / High"],
]

append_to_file('cometchat-test-cases/Group_Actions/Group_Actions_Test_Cases.xlsx', ga_expand)


# ============================================================
# 9. GROUPS MODULE — Expand
# ============================================================
print("\n9. GROUPS MODULE")
groups_expand = [
    # --- Integration ---
    ["GROUPS_032", "Positive", "Integration: Groups Module with Chat", "User is logged in and on Groups tab",
     "Verify clicking group opens group chat",
     "1. Click on a group in the list.\n2. Observe chat area.",
     "Group chat should open with message history and group header info.",
     "High / High"],
    ["GROUPS_033", "", "Integration: Groups Module with Group Actions", "",
     "Verify group info accessible from group list",
     "1. Long press or click info on a group in the list.",
     "Group info/actions panel should open.",
     "Medium / Medium"],

    # --- Regression ---
    ["GROUPS_034", "Positive", "Regression: Groups Module", "User is logged in",
     "Verify group list updates after creating a new group",
     "1. Create a new group.\n2. Go back to group list.",
     "Newly created group should appear in the list.",
     "High / High"],
    ["GROUPS_035", "", "", "",
     "Verify group list updates after leaving a group",
     "1. Leave a group.\n2. Observe group list.",
     "Left group should be removed from the list or marked appropriately.",
     "High / High"],
    ["GROUPS_036", "", "", "",
     "Verify group list after deleting a group",
     "1. Delete a group (as owner).\n2. Observe group list.",
     "Deleted group should be removed from the list for all members.",
     "High / High"],

    # --- Security ---
    ["GROUPS_037", "Negative", "Security: Groups Module", "User is logged in",
     "Verify private groups not visible to non-members",
     "1. Observe group list as a non-member.",
     "Private groups should not appear in the group list for non-members.",
     "High / Critical"],
    ["GROUPS_038", "", "", "",
     "Verify password-protected group requires password to join",
     "1. Click join on a password-protected group.\n2. Enter wrong password.",
     "Should reject with 'Incorrect password' error. Should not allow entry.",
     "High / Critical"],
    ["GROUPS_039", "", "", "",
     "Verify group creation validates input",
     "1. Try to create a group with empty name.\n2. Try with special characters.\n3. Try with very long name.",
     "Empty name should be rejected. Special chars should be handled. Long name should truncate or reject.",
     "High / High"],

    # --- Edge Cases ---
    ["GROUPS_040", "Positive", "Edge Case: Groups Module", "User is logged in",
     "Verify group list with 500+ groups",
     "1. Have an account that's part of 500+ groups.\n2. Open groups tab.",
     "Groups should load with pagination/infinite scroll. No performance issues.",
     "Medium / High"],
    ["GROUPS_041", "", "", "",
     "Verify creating group with duplicate name",
     "1. Create a group with a name that already exists.",
     "Should either allow (with different ID) or show warning about duplicate name.",
     "Medium / Medium"],
    ["GROUPS_042", "", "", "",
     "Verify group with emoji in name",
     "1. Create a group named '🚀 Rocket Team'.\n2. Observe in group list.",
     "Group name with emoji should display correctly.",
     "Low / Low"],
    ["GROUPS_043", "Negative", "", "",
     "Verify group creation without network",
     "1. Disconnect network.\n2. Try to create a group.",
     "Error message should display. Group should not be created.",
     "High / High"],

    # --- Boundary Values ---
    ["GROUPS_044", "Positive", "Boundary: Groups Module", "User is logged in",
     "Verify group list with exactly 0 groups",
     "1. Login with account not part of any group.",
     "Empty state should display with 'No groups' message and create button.",
     "Medium / Medium"],
    ["GROUPS_045", "", "", "",
     "Verify group name with exactly 1 character",
     "1. Create a group with name 'A'.",
     "Group should be created successfully with single character name.",
     "Low / Low"],
    ["GROUPS_046", "", "", "",
     "Verify group name at maximum length",
     "1. Create a group with name at max character limit.",
     "Group should be created. Name should display (possibly truncated in list).",
     "Medium / Medium"],

    # --- Equivalence Partitioning ---
    ["GROUPS_047", "Positive", "Equivalence Partitioning: Group Types", "User is logged in",
     "Verify public group display and join",
     "1. Observe a public group in list.\n2. Click join.",
     "Public group should show join button. Joining should be immediate without approval.",
     "High / High"],
    ["GROUPS_048", "", "", "",
     "Verify private group display and join",
     "1. Observe a private group (if visible).\n2. Try to join.",
     "Private group should require invitation. No direct join option.",
     "High / High"],
    ["GROUPS_049", "", "", "",
     "Verify password-protected group display and join",
     "1. Observe a password-protected group.\n2. Click join.\n3. Enter correct password.",
     "Should prompt for password. Correct password should allow joining.",
     "High / High"],
]

append_to_file('cometchat-test-cases/Groups_Module/Groups_Module_Test_Cases.xlsx', groups_expand)


# ============================================================
# 10. USER MODULE — Expand
# ============================================================
print("\n10. USER MODULE")
users_expand = [
    # --- Integration ---
    ["USERS_026", "Positive", "Integration: User Module with Chat", "User is logged in and on Users tab",
     "Verify clicking user opens one-on-one chat",
     "1. Click on a user in the list.",
     "One-on-one chat should open with that user. Message history should load.",
     "High / High"],
    ["USERS_027", "", "Integration: User Module with Conversation List", "",
     "Verify starting chat from users list creates conversation",
     "1. Click on a user with no prior conversation.\n2. Send a message.",
     "New conversation should appear in conversation list after sending first message.",
     "High / High"],

    # --- Regression ---
    ["USERS_028", "Positive", "Regression: User Module", "User is logged in",
     "Verify user list updates when new user registers",
     "1. A new user registers on the platform.\n2. Refresh user list.",
     "New user should appear in the user list.",
     "Medium / Medium"],
    ["USERS_029", "", "", "",
     "Verify user list after blocking a user",
     "1. Block a user.\n2. Observe user list.",
     "Blocked user should be handled per policy (hidden, marked, or unchanged in list).",
     "Medium / Medium"],
    ["USERS_030", "", "", "",
     "Verify user list after unblocking a user",
     "1. Unblock a previously blocked user.\n2. Observe user list.",
     "User should be accessible again in the list.",
     "Medium / Medium"],
    ["USERS_031", "", "", "",
     "Verify user online status updates in real-time",
     "1. Observe a user in the list.\n2. That user goes online/offline.",
     "Online status indicator should update in real-time.",
     "High / High"],

    # --- Security ---
    ["USERS_032", "Negative", "Security: User Module", "User is not logged in",
     "Verify user list not accessible without authentication",
     "1. Try to access user list without logging in.",
     "Should redirect to login. No user data exposed.",
     "High / Critical"],
    ["USERS_033", "", "", "User is logged in",
     "Verify user list does not expose sensitive user data",
     "1. Observe user list entries.",
     "Only public info (name, avatar, status) should display. No email, phone, or private data.",
     "High / Critical"],
    ["USERS_034", "", "", "",
     "Verify XSS prevention in user search",
     "1. Type '<script>alert(1)</script>' in user search.",
     "Input should be sanitized. No script execution.",
     "High / Critical"],

    # --- Edge Cases ---
    ["USERS_035", "Positive", "Edge Case: User Module", "User is logged in",
     "Verify user list with 10000+ users",
     "1. Open users tab on a platform with 10000+ users.",
     "Users should load with pagination/infinite scroll. Alphabetical grouping should work.",
     "Medium / High"],
    ["USERS_036", "", "", "",
     "Verify user with very long name",
     "1. Observe a user with a 100+ character name in the list.",
     "Name should truncate with ellipsis. No layout breaking.",
     "Medium / Medium"],
    ["USERS_037", "", "", "",
     "Verify user with special characters in name",
     "1. Observe a user with emojis, unicode, or special chars in name.",
     "Name should display correctly.",
     "Low / Medium"],
    ["USERS_038", "", "", "",
     "Verify user search with partial name",
     "1. Search for first 2 characters of a user's name.",
     "All users matching the partial name should appear.",
     "High / High"],
    ["USERS_039", "Negative", "", "",
     "Verify user list when server returns error",
     "1. Simulate server error.\n2. Open users tab.",
     "Error message should display with retry option. No crash.",
     "High / High"],

    # --- Boundary Values ---
    ["USERS_040", "Positive", "Boundary: User Module", "User is logged in",
     "Verify user list with exactly 0 users (only self)",
     "1. Login on a platform with no other users.",
     "Empty state should display or only self should appear.",
     "Medium / Medium"],
    ["USERS_041", "", "", "",
     "Verify user list with exactly 1 other user",
     "1. Login on a platform with 1 other user.",
     "Single user should display correctly with all elements.",
     "Low / Low"],
    ["USERS_042", "", "", "",
     "Verify search with exactly 1 character",
     "1. Type a single character in user search.",
     "Should filter users or show minimum character requirement.",
     "Medium / Medium"],

    # --- Equivalence Partitioning ---
    ["USERS_043", "Positive", "Equivalence Partitioning: User Status", "User is logged in",
     "Verify online user display",
     "1. Observe an online user in the list.",
     "Should show green online indicator and be at top of list (if sorted by status).",
     "High / High"],
    ["USERS_044", "", "", "",
     "Verify offline user display",
     "1. Observe an offline user in the list.",
     "Should show grey/no indicator. Last seen time may display.",
     "High / High"],
    ["USERS_045", "", "", "",
     "Verify away/busy user display (if supported)",
     "1. Observe a user with away/busy status.",
     "Should show appropriate status indicator (yellow/red dot).",
     "Medium / Medium"],
]

append_to_file('cometchat-test-cases/User_Module/Users_Module_Test_Script.xlsx', users_expand)


# ============================================================
# 11. CALL MODULE — Expand
# ============================================================
print("\n11. CALL MODULE")
calls_expand = [
    # --- Integration ---
    ["CALLS_063", "Positive", "Integration: Call Module with Message List", "User is logged in",
     "Verify call log entry created after completing a call",
     "1. Make a call.\n2. End call.\n3. Check call logs.",
     "New call log entry should appear with correct caller, duration, and timestamp.",
     "High / High"],
    ["CALLS_064", "", "Integration: Call Module with Conversation List", "",
     "Verify call creates/updates conversation in conversation list",
     "1. Make a call to a user.\n2. Check conversation list.",
     "Conversation with that user should show call activity (e.g., 'Voice call - 2:30').",
     "Medium / Medium"],
    ["CALLS_065", "", "Integration: Call Module with Notifications", "",
     "Verify missed call notification",
     "1. Call User B.\n2. User B doesn't answer.\n3. Check User B's notifications.",
     "User B should receive a missed call notification with caller info.",
     "High / High"],

    # --- Regression ---
    ["CALLS_066", "Positive", "Regression: Call Module", "User is logged in",
     "Verify call logs persist after app restart",
     "1. Make several calls.\n2. Close and reopen app.\n3. Check call logs.",
     "All call logs should be intact with correct details.",
     "High / High"],
    ["CALLS_067", "", "", "",
     "Verify call functionality after network reconnection",
     "1. Lose network.\n2. Reconnect.\n3. Make a call.",
     "Call should work normally after network reconnection.",
     "High / High"],
    ["CALLS_068", "", "", "",
     "Verify call logs after clearing call history",
     "1. Clear call history.\n2. Make a new call.\n3. Check logs.",
     "Only the new call should appear. Old logs should be cleared.",
     "Medium / Medium"],

    # --- Security ---
    ["CALLS_069", "Negative", "Security: Call Module", "User is logged in",
     "Verify call cannot be initiated to blocked user",
     "1. Block a user.\n2. Try to call that user.",
     "Call should be blocked with appropriate message.",
     "High / Critical"],
    ["CALLS_070", "", "", "",
     "Verify call audio/video stream is encrypted",
     "1. Initiate a call.\n2. Inspect network traffic.",
     "Media streams should be encrypted (SRTP/DTLS). No plain media in transit.",
     "High / Critical"],
    ["CALLS_071", "", "", "",
     "Verify call logs only show user's own calls",
     "1. Login as User A.\n2. Check call logs.",
     "Only calls involving User A should display. No other users' call history visible.",
     "High / Critical"],
    ["CALLS_072", "", "", "User is not logged in",
     "Verify call module not accessible without authentication",
     "1. Try to access call logs without logging in.",
     "Should redirect to login. No call data exposed.",
     "High / Critical"],

    # --- Edge Cases ---
    ["CALLS_073", "Positive", "Edge Case: Call Module", "User is logged in",
     "Verify call behavior when switching between WiFi and cellular",
     "1. Start a call on WiFi.\n2. Switch to cellular mid-call.",
     "Call should continue with brief interruption or seamless handoff.",
     "High / High"],
    ["CALLS_074", "", "", "",
     "Verify call with very long duration (1+ hour)",
     "1. Maintain a call for 1+ hour.\n2. End call.\n3. Check log.",
     "Call should remain stable. Log should show correct duration.",
     "Medium / Medium"],
    ["CALLS_075", "", "", "",
     "Verify multiple simultaneous group calls",
     "1. Have two different groups initiate calls at the same time.",
     "User should receive both notifications. Can join one at a time.",
     "Medium / High"],
    ["CALLS_076", "", "", "",
     "Verify call log with 1000+ entries",
     "1. Have 1000+ call log entries.\n2. Open call logs.",
     "Logs should load with pagination. No performance issues.",
     "Medium / Medium"],
    ["CALLS_077", "Negative", "", "",
     "Verify call when microphone permission is denied",
     "1. Deny microphone permission.\n2. Try to make an audio call.",
     "Should show permission request or error message. Call should not proceed without mic.",
     "High / High"],
    ["CALLS_078", "", "", "",
     "Verify video call when camera permission is denied",
     "1. Deny camera permission.\n2. Try to make a video call.",
     "Should show permission request or fall back to audio-only call.",
     "High / High"],

    # --- Boundary Values ---
    ["CALLS_079", "Positive", "Boundary: Call Module", "User is logged in",
     "Verify call log with exactly 0 entries",
     "1. Login with new account.\n2. Open call logs.",
     "Empty state should display with appropriate message.",
     "Medium / Medium"],
    ["CALLS_080", "", "", "",
     "Verify call log with exactly 1 entry",
     "1. Make one call.\n2. Open call logs.",
     "Single call log should display correctly with all details.",
     "Low / Low"],
    ["CALLS_081", "", "", "",
     "Verify call duration of 0 seconds (immediate hang up)",
     "1. Call and immediately hang up.\n2. Check call log.",
     "Call should log as missed or with 0:00 duration.",
     "Medium / Medium"],
    ["CALLS_082", "", "", "",
     "Verify group call with maximum participants",
     "1. Start a group call with maximum allowed participants.",
     "All participants should connect. Audio/video should work for all.",
     "High / High"],

    # --- Equivalence Partitioning ---
    ["CALLS_083", "Positive", "Equivalence Partitioning: Call Types", "User is logged in",
     "Verify one-on-one audio call",
     "1. Make an audio call to a single user.",
     "Audio call should connect with clear audio both ways.",
     "High / High"],
    ["CALLS_084", "", "", "",
     "Verify one-on-one video call",
     "1. Make a video call to a single user.",
     "Video call should connect with video and audio both ways.",
     "High / High"],
    ["CALLS_085", "", "", "",
     "Verify group audio call",
     "1. Make an audio call in a group.",
     "All participants should hear each other.",
     "High / High"],
    ["CALLS_086", "", "", "",
     "Verify group video call",
     "1. Make a video call in a group.",
     "All participants should see and hear each other. Grid/tile layout should adjust.",
     "High / High"],
    ["CALLS_087", "", "Equivalence Partitioning: Call Log Types", "",
     "Verify outgoing call log display",
     "1. Make an outgoing call.\n2. Check call log.",
     "Should show outgoing call icon, contact name, duration, and timestamp.",
     "High / High"],
    ["CALLS_088", "", "", "",
     "Verify incoming call log display",
     "1. Receive and answer an incoming call.\n2. Check call log.",
     "Should show incoming call icon, caller name, duration, and timestamp.",
     "High / High"],
    ["CALLS_089", "", "", "",
     "Verify missed call log display",
     "1. Miss an incoming call.\n2. Check call log.",
     "Should show missed call icon (red), caller name, and timestamp. No duration.",
     "High / High"],
    ["CALLS_090", "", "", "",
     "Verify rejected call log display",
     "1. Reject an incoming call.\n2. Check call log.",
     "Should show rejected/missed call entry with appropriate icon.",
     "Medium / Medium"],
]

append_to_file('cometchat-test-cases/Call_Module/Calls_Module_Test_Cases.xlsx', calls_expand)

print("\n" + "="*60)
print("ALL EXPANSIONS COMPLETE!")
print("="*60)
