import openpyxl
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side

def style_sheet(ws):
    header_font = Font(bold=True, size=11)
    header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
    header_font_white = Font(bold=True, size=11, color="FFFFFF")
    thin_border = Border(
        left=Side(style='thin'), right=Side(style='thin'),
        top=Side(style='thin'), bottom=Side(style='thin')
    )
    wrap = Alignment(wrap_text=True, vertical='top')

    for col in range(1, ws.max_column + 1):
        cell = ws.cell(row=1, column=col)
        cell.font = header_font_white
        cell.fill = header_fill
        cell.alignment = Alignment(wrap_text=True, vertical='center', horizontal='center')
        cell.border = thin_border

    for row in range(2, ws.max_row + 1):
        for col in range(1, ws.max_column + 1):
            cell = ws.cell(row=row, column=col)
            cell.alignment = wrap
            cell.border = thin_border

    ws.column_dimensions['A'].width = 14
    ws.column_dimensions['B'].width = 12
    ws.column_dimensions['C'].width = 30
    ws.column_dimensions['D'].width = 30
    ws.column_dimensions['E'].width = 40
    ws.column_dimensions['F'].width = 45
    ws.column_dimensions['G'].width = 40
    ws.column_dimensions['H'].width = 18

def create_workbook(sheet_name, headers, data, filename):
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = sheet_name
    ws.append(headers)
    for row in data:
        ws.append(row)
    style_sheet(ws)
    wb.save(filename)
    print(f"Created: {filename} ({len(data)} test cases)")

headers = ["TestCase_ID", "Sentiment", "Test Scenario", "Precondition", "Test Case", "Steps", "Expected Results", "Priority / Severity"]

# ============================================================
# 1. MESSAGE LIST TEST CASES
# ============================================================
message_list_data = [
    # --- Verify Message List Display ---
    ["ML_001", "Positive", "Verify Message List Display", "User is logged in and chat is open",
     "Verify message list loads correctly",
     "1. Open any conversation.\n2. Observe message list area.",
     "Messages should load and display in chronological order with sender info and timestamps.",
     "High / High"],
    ["ML_002", "", "", "",
     "Verify sender message alignment (right side)",
     "1. Open a conversation.\n2. Observe sent messages.",
     "Sender's messages should appear on the right side of the chat.",
     "High / High"],
    ["ML_003", "", "", "",
     "Verify receiver message alignment (left side)",
     "1. Open a conversation.\n2. Observe received messages.",
     "Receiver's messages should appear on the left side of the chat.",
     "High / High"],
    ["ML_004", "", "", "",
     "Verify user name displayed above messages",
     "1. Open a group conversation.\n2. Observe messages from different users.",
     "Sender's name should display above their message bubble in group chats.",
     "High / High"],
    ["ML_005", "", "", "",
     "Verify user avatar displayed next to messages",
     "1. Open a group conversation.\n2. Observe avatars next to messages.",
     "Sender's avatar/profile picture should display next to their messages.",
     "Medium / Medium"],
    ["ML_006", "", "", "",
     "Verify message timestamp display",
     "1. Open a conversation.\n2. Observe timestamps on messages.",
     "Each message should display time in readable format (e.g., '02:35 PM').",
     "High / High"],
    ["ML_007", "", "", "",
     "Verify date separator between different days",
     "1. Open a conversation with messages spanning multiple days.\n2. Observe date separators.",
     "Date separator (e.g., 'Today', 'Yesterday', 'Feb 15, 2025') should appear between messages of different days.",
     "High / Medium"],
    ["ML_008", "", "", "",
     "Verify scroll to load older messages",
     "1. Open a conversation with many messages.\n2. Scroll up to the top.",
     "Older messages should load as user scrolls up. Loading indicator should appear during fetch.",
     "High / High"],
    ["ML_009", "", "", "",
     "Verify auto-scroll to latest message on open",
     "1. Open a conversation with many messages.",
     "Chat should auto-scroll to the most recent message at the bottom.",
     "High / High"],
    ["ML_010", "", "", "",
     "Verify new incoming message auto-scrolls",
     "1. Be at the bottom of a conversation.\n2. Receive a new message.",
     "Chat should auto-scroll to show the new incoming message.",
     "High / High"],
    ["ML_011", "Negative", "Verify Message List Display", "User is logged in, no messages in conversation",
     "Verify empty message list state",
     "1. Open a new conversation with no messages.",
     "Empty state or placeholder message should display (e.g., 'No messages yet').",
     "Medium / Medium"],
    ["ML_012", "", "", "User is logged in, network disconnected",
     "Verify message list behavior without network",
     "1. Disconnect network.\n2. Open a conversation.",
     "Cached messages should display or appropriate error message should show.",
     "High / High"],

    # --- Verify Reactions ---
    ["ML_013", "Positive", "Verify Reactions", "User is logged in and chat is open",
     "Verify adding a reaction to a message",
     "1. Long press or hover on a message.\n2. Select a reaction emoji.",
     "Reaction should appear below the message with count of 1.",
     "High / High"],
    ["ML_014", "", "", "",
     "Verify multiple reactions on a message",
     "1. Add different reactions from different users on the same message.",
     "All unique reactions should display below the message with respective counts.",
     "High / High"],
    ["ML_015", "", "", "",
     "Verify reaction count increments",
     "1. Have multiple users react with the same emoji on a message.",
     "Reaction count should increment correctly (e.g., 👍 3).",
     "High / Medium"],
    ["ML_016", "", "", "",
     "Verify removing own reaction",
     "1. Tap on your own reaction on a message.",
     "Reaction should be removed. Count should decrement or reaction should disappear if count reaches 0.",
     "High / High"],
    ["ML_017", "", "", "",
     "Verify reaction details/list",
     "1. Long press or click on a reaction below a message.",
     "List of users who reacted with that emoji should display.",
     "Medium / Medium"],
    ["ML_018", "Negative", "Verify Reactions", "User is logged in, network disconnected",
     "Verify reaction fails without network",
     "1. Disconnect network.\n2. Try to add a reaction.",
     "Error message should display or reaction should queue for retry.",
     "High / High"],

    # --- Verify Reply ---
    ["ML_019", "Positive", "Verify Reply", "User is logged in and chat is open",
     "Verify reply option available on message",
     "1. Long press or hover on a message.\n2. Observe message menu.",
     "Reply option should be available in the message action menu.",
     "High / High"],
    ["ML_020", "", "", "",
     "Verify reply shows original message preview",
     "1. Select reply on a message.\n2. Observe composer area.",
     "Original message preview should appear above the input field with close button.",
     "High / High"],
    ["ML_021", "", "", "",
     "Verify sending a reply message",
     "1. Select reply on a message.\n2. Type reply text.\n3. Send.",
     "Reply should appear in chat with reference to the original message (quoted).",
     "High / High"],
    ["ML_022", "", "", "",
     "Verify tapping on replied message scrolls to original",
     "1. Tap on the quoted/original message in a reply bubble.",
     "Chat should scroll to the original message and highlight it briefly.",
     "Medium / Medium"],
    ["ML_023", "", "", "",
     "Verify cancel reply",
     "1. Select reply on a message.\n2. Click close/cancel on the reply preview.",
     "Reply preview should dismiss and composer should return to normal state.",
     "Medium / Medium"],

    # --- Verify Reply In Thread ---
    ["ML_024", "Positive", "Verify Reply In Thread", "User is logged in and chat is open",
     "Verify 'Reply In Thread' option in message menu",
     "1. Long press or hover on a message.\n2. Observe message menu.",
     "'Reply In Thread' option should be available.",
     "High / High"],
    ["ML_025", "", "", "",
     "Verify thread panel opens on 'Reply In Thread'",
     "1. Click 'Reply In Thread' on a message.",
     "Thread panel should open showing the original message and thread replies.",
     "High / High"],
    ["ML_026", "", "", "",
     "Verify thread reply count on parent message",
     "1. Reply in a thread.\n2. Go back to main chat.",
     "Parent message should show thread reply count (e.g., '3 replies').",
     "High / High"],
    ["ML_027", "", "", "",
     "Verify clicking thread count opens thread",
     "1. Click on thread reply count on a parent message.",
     "Thread panel should open with all thread replies.",
     "High / Medium"],

    # --- Verify Copy ---
    ["ML_028", "Positive", "Verify Copy Message", "User is logged in and chat is open",
     "Verify 'Copy' option in message menu",
     "1. Long press or hover on a text message.\n2. Observe message menu.",
     "'Copy' option should be available.",
     "High / High"],
    ["ML_029", "", "", "",
     "Verify copying text message",
     "1. Click 'Copy' on a text message.\n2. Paste in input field.",
     "Message text should be copied to clipboard and paste correctly.",
     "High / High"],
    ["ML_030", "Negative", "Verify Copy Message", "User is logged in and chat is open",
     "Verify copy not available for media-only messages",
     "1. Long press on an image/video message with no caption.",
     "'Copy' option should not appear or be disabled for media-only messages.",
     "Low / Low"],

    # --- Verify Edit ---
    ["ML_031", "Positive", "Verify Edit Message", "User is logged in and chat is open",
     "Verify 'Edit' option for own messages",
     "1. Long press or hover on own sent text message.\n2. Observe message menu.",
     "'Edit' option should be available for own messages only.",
     "High / High"],
    ["ML_032", "", "", "",
     "Verify editing a message",
     "1. Click 'Edit' on own message.\n2. Modify text.\n3. Save/Send.",
     "Message should update with new text and show 'edited' indicator.",
     "High / High"],
    ["ML_033", "", "", "",
     "Verify cancel edit",
     "1. Click 'Edit' on own message.\n2. Click cancel.",
     "Edit mode should dismiss and original message should remain unchanged.",
     "Medium / Medium"],
    ["ML_034", "Negative", "Verify Edit Message", "User is logged in and chat is open",
     "Verify 'Edit' not available for others' messages",
     "1. Long press on another user's message.\n2. Observe message menu.",
     "'Edit' option should NOT appear for messages sent by other users.",
     "High / High"],

    # --- Verify Info ---
    ["ML_035", "Positive", "Verify Message Info", "User is logged in and chat is open",
     "Verify 'Info' option in message menu",
     "1. Long press or hover on own message.\n2. Observe message menu.",
     "'Info' option should be available.",
     "High / High"],
    ["ML_036", "", "", "",
     "Verify message info shows delivery details",
     "1. Click 'Info' on own message.",
     "Message info panel should show sent time, delivered time, and read time.",
     "High / High"],
    ["ML_037", "", "", "",
     "Verify message info in group shows read/delivered by",
     "1. Click 'Info' on own message in a group chat.",
     "Info should show list of members with delivered and read status for each.",
     "High / Medium"],

    # --- Verify Delete ---
    ["ML_038", "Positive", "Verify Delete Message", "User is logged in and chat is open",
     "Verify 'Delete' option for own messages",
     "1. Long press or hover on own message.\n2. Observe message menu.",
     "'Delete' option should be available for own messages.",
     "High / High"],
    ["ML_039", "", "", "",
     "Verify delete confirmation dialog",
     "1. Click 'Delete' on own message.",
     "Confirmation dialog should appear asking to confirm deletion.",
     "High / High"],
    ["ML_040", "", "", "",
     "Verify message deleted on confirm",
     "1. Click confirm in delete dialog.",
     "Message should be removed or replaced with 'This message was deleted' text.",
     "High / High"],
    ["ML_041", "", "", "",
     "Verify cancel delete keeps message",
     "1. Click cancel in delete dialog.",
     "Message should remain unchanged in the chat.",
     "Medium / Medium"],
    ["ML_042", "Negative", "Verify Delete Message", "User is logged in and chat is open",
     "Verify 'Delete' not available for others' messages",
     "1. Long press on another user's message.\n2. Observe message menu.",
     "'Delete' option should NOT appear for messages sent by other users (unless admin).",
     "High / High"],
    ["ML_043", "", "", "User is logged in, network disconnected",
     "Verify delete fails without network",
     "1. Disconnect network.\n2. Try to delete a message.",
     "Error message should display indicating network issue.",
     "High / High"],

    # --- Verify Notifications ---
    ["ML_044", "Positive", "Verify Notifications", "User is logged in and app is in background",
     "Verify push notification for new message",
     "1. Send a message from another user.\n2. Observe notification on device.",
     "Push notification should appear with sender name and message preview.",
     "High / High"],
    ["ML_045", "", "", "",
     "Verify notification tap opens correct conversation",
     "1. Receive a notification.\n2. Tap on it.",
     "App should open and navigate to the correct conversation with the new message.",
     "High / High"],
    ["ML_046", "", "", "User is logged in and chat is open in foreground",
     "Verify in-app notification for message in different chat",
     "1. Be in conversation A.\n2. Receive message in conversation B.",
     "In-app notification/banner should appear for the new message in conversation B.",
     "Medium / Medium"],
    ["ML_047", "Negative", "Verify Notifications", "User has notifications disabled",
     "Verify no notification when disabled",
     "1. Disable notifications in settings.\n2. Receive a message.",
     "No push notification should appear.",
     "Medium / Medium"],

    # --- Verify Calling from Message List ---
    ["ML_048", "Positive", "Verify Calling from Message List", "User is logged in and one-on-one chat is open",
     "Verify audio call button in chat header",
     "1. Open a one-on-one conversation.\n2. Observe chat header.",
     "Audio call icon should be visible in the chat header.",
     "High / High"],
    ["ML_049", "", "", "",
     "Verify video call button in chat header",
     "1. Open a one-on-one conversation.\n2. Observe chat header.",
     "Video call icon should be visible in the chat header.",
     "High / High"],
    ["ML_050", "", "", "",
     "Verify initiating audio call from chat",
     "1. Click audio call icon in chat header.",
     "Audio call should initiate with the user. Call screen should appear.",
     "High / High"],
    ["ML_051", "", "", "",
     "Verify initiating video call from chat",
     "1. Click video call icon in chat header.",
     "Video call should initiate with the user. Video call screen should appear.",
     "High / High"],
    ["ML_052", "", "", "User is logged in and group chat is open",
     "Verify group call button in group chat header",
     "1. Open a group conversation.\n2. Observe chat header.",
     "Group call icon should be visible in the group chat header.",
     "High / High"],

    # --- Verify Group Actions from Message List ---
    ["ML_053", "Positive", "Verify Group Actions in Message List", "User is logged in and group chat is open",
     "Verify group info accessible from chat header",
     "1. Open a group conversation.\n2. Click on group name or info icon in header.",
     "Group info panel should open showing group details, members, and actions.",
     "High / High"],
    ["ML_054", "", "", "",
     "Verify member join/leave messages in chat",
     "1. Have a member join or leave the group.\n2. Observe message list.",
     "System message should appear (e.g., 'John joined the group', 'Jane left the group').",
     "High / Medium"],
    ["ML_055", "", "", "",
     "Verify admin action messages in chat",
     "1. Admin kicks/bans a member or changes scope.\n2. Observe message list.",
     "System message should appear reflecting the admin action.",
     "Medium / Medium"],

    # --- Verify Message Types Display ---
    ["ML_056", "Positive", "Verify Message Types Display", "User is logged in and chat is open",
     "Verify text message display",
     "1. Send/receive a text message.\n2. Observe in message list.",
     "Text message should display in a message bubble with proper formatting.",
     "High / High"],
    ["ML_057", "", "", "",
     "Verify image message display",
     "1. Send/receive an image.\n2. Observe in message list.",
     "Image should display as thumbnail in chat. Tapping should open full-size preview.",
     "High / High"],
    ["ML_058", "", "", "",
     "Verify video message display",
     "1. Send/receive a video.\n2. Observe in message list.",
     "Video thumbnail with play icon should display. Tapping should play the video.",
     "High / High"],
    ["ML_059", "", "", "",
     "Verify audio message display",
     "1. Send/receive an audio message.\n2. Observe in message list.",
     "Audio player with play/pause button and duration should display.",
     "High / High"],
    ["ML_060", "", "", "",
     "Verify document/file message display",
     "1. Send/receive a document.\n2. Observe in message list.",
     "File icon with file name and size should display. Tapping should download/open.",
     "High / High"],
    ["ML_061", "", "", "",
     "Verify link preview in message",
     "1. Send a message containing a URL.\n2. Observe in message list.",
     "Link preview with title, description, and thumbnail should display below the message.",
     "Medium / Medium"],
    ["ML_062", "", "", "",
     "Verify sticker message display",
     "1. Send/receive a sticker.\n2. Observe in message list.",
     "Sticker should display as a larger image without message bubble.",
     "Medium / Medium"],
    ["ML_063", "", "", "",
     "Verify emoji-only message display",
     "1. Send a message with only emojis (1-3).\n2. Observe in message list.",
     "Emojis should display in larger size without message bubble background.",
     "Low / Low"],
]


# ============================================================
# 2. ADVANCED SEARCH TEST CASES
# ============================================================
advanced_search_data = [
    # --- Verify Advanced Search UI ---
    ["AS_001", "Positive", "Verify Advanced Search UI", "User is logged in",
     "Verify advanced search icon/button is visible",
     "1. Navigate to Chats tab.\n2. Observe search area.",
     "Advanced search icon or button should be visible and accessible.",
     "High / High"],
    ["AS_002", "", "", "",
     "Verify advanced search panel opens",
     "1. Click on advanced search icon/button.",
     "Advanced search panel should open with category filters (Audio, Documents, Photos, Videos, Links, Text Message).",
     "High / High"],
    ["AS_003", "", "", "",
     "Verify search input field in advanced search",
     "1. Open advanced search panel.\n2. Observe search input.",
     "Search input field should be visible with placeholder text.",
     "High / High"],
    ["AS_004", "", "", "",
     "Verify closing advanced search panel",
     "1. Open advanced search.\n2. Click close/back button.",
     "Advanced search panel should close and return to previous view.",
     "Medium / Medium"],

    # --- Verify Audio Search ---
    ["AS_005", "Positive", "Verify Audio Search", "User is logged in and has audio messages in conversations",
     "Verify audio filter displays audio messages",
     "1. Open advanced search.\n2. Select 'Audio' filter.",
     "All audio messages across conversations should display in results.",
     "High / High"],
    ["AS_006", "", "", "",
     "Verify audio result shows sender and conversation info",
     "1. Select 'Audio' filter.\n2. Observe results.",
     "Each audio result should show sender name, conversation name, date, and duration.",
     "Medium / Medium"],
    ["AS_007", "", "", "",
     "Verify tapping audio result opens conversation",
     "1. Select 'Audio' filter.\n2. Tap on an audio result.",
     "Should navigate to the conversation and highlight/scroll to the audio message.",
     "High / High"],
    ["AS_008", "Negative", "Verify Audio Search", "User is logged in with no audio messages",
     "Verify empty state for audio search",
     "1. Open advanced search.\n2. Select 'Audio' filter.",
     "Empty state message should display (e.g., 'No audio messages found').",
     "Medium / Medium"],

    # --- Verify Documents Search ---
    ["AS_009", "Positive", "Verify Documents Search", "User is logged in and has document messages in conversations",
     "Verify documents filter displays document messages",
     "1. Open advanced search.\n2. Select 'Documents' filter.",
     "All document/file messages across conversations should display in results.",
     "High / High"],
    ["AS_010", "", "", "",
     "Verify document result shows file details",
     "1. Select 'Documents' filter.\n2. Observe results.",
     "Each result should show file name, file type icon, size, sender, and date.",
     "Medium / Medium"],
    ["AS_011", "", "", "",
     "Verify tapping document result opens conversation",
     "1. Select 'Documents' filter.\n2. Tap on a document result.",
     "Should navigate to the conversation and highlight/scroll to the document message.",
     "High / High"],
    ["AS_012", "Negative", "Verify Documents Search", "User is logged in with no document messages",
     "Verify empty state for documents search",
     "1. Open advanced search.\n2. Select 'Documents' filter.",
     "Empty state message should display (e.g., 'No documents found').",
     "Medium / Medium"],

    # --- Verify Photos Search ---
    ["AS_013", "Positive", "Verify Photos Search", "User is logged in and has image messages in conversations",
     "Verify photos filter displays image messages",
     "1. Open advanced search.\n2. Select 'Photos' filter.",
     "All image messages across conversations should display as a grid/list.",
     "High / High"],
    ["AS_014", "", "", "",
     "Verify photo thumbnails display correctly",
     "1. Select 'Photos' filter.\n2. Observe results.",
     "Photo thumbnails should load and display correctly with sender and date info.",
     "Medium / Medium"],
    ["AS_015", "", "", "",
     "Verify tapping photo result opens conversation",
     "1. Select 'Photos' filter.\n2. Tap on a photo result.",
     "Should navigate to the conversation and highlight/scroll to the image message.",
     "High / High"],
    ["AS_016", "", "", "",
     "Verify photo preview from search results",
     "1. Select 'Photos' filter.\n2. Long press or preview a photo.",
     "Full-size photo preview should open.",
     "Medium / Medium"],
    ["AS_017", "Negative", "Verify Photos Search", "User is logged in with no image messages",
     "Verify empty state for photos search",
     "1. Open advanced search.\n2. Select 'Photos' filter.",
     "Empty state message should display (e.g., 'No photos found').",
     "Medium / Medium"],

    # --- Verify Videos Search ---
    ["AS_018", "Positive", "Verify Videos Search", "User is logged in and has video messages in conversations",
     "Verify videos filter displays video messages",
     "1. Open advanced search.\n2. Select 'Videos' filter.",
     "All video messages across conversations should display in results.",
     "High / High"],
    ["AS_019", "", "", "",
     "Verify video result shows thumbnail and duration",
     "1. Select 'Videos' filter.\n2. Observe results.",
     "Each video result should show thumbnail, play icon, duration, sender, and date.",
     "Medium / Medium"],
    ["AS_020", "", "", "",
     "Verify tapping video result opens conversation",
     "1. Select 'Videos' filter.\n2. Tap on a video result.",
     "Should navigate to the conversation and highlight/scroll to the video message.",
     "High / High"],
    ["AS_021", "Negative", "Verify Videos Search", "User is logged in with no video messages",
     "Verify empty state for videos search",
     "1. Open advanced search.\n2. Select 'Videos' filter.",
     "Empty state message should display (e.g., 'No videos found').",
     "Medium / Medium"],

    # --- Verify Links Search ---
    ["AS_022", "Positive", "Verify Links Search", "User is logged in and has messages with links",
     "Verify links filter displays messages with URLs",
     "1. Open advanced search.\n2. Select 'Links' filter.",
     "All messages containing URLs across conversations should display.",
     "High / High"],
    ["AS_023", "", "", "",
     "Verify link result shows URL and preview",
     "1. Select 'Links' filter.\n2. Observe results.",
     "Each result should show the URL, link preview (title/thumbnail if available), sender, and date.",
     "Medium / Medium"],
    ["AS_024", "", "", "",
     "Verify tapping link result opens conversation",
     "1. Select 'Links' filter.\n2. Tap on a link result.",
     "Should navigate to the conversation and highlight/scroll to the message with the link.",
     "High / High"],
    ["AS_025", "Negative", "Verify Links Search", "User is logged in with no link messages",
     "Verify empty state for links search",
     "1. Open advanced search.\n2. Select 'Links' filter.",
     "Empty state message should display (e.g., 'No links found').",
     "Medium / Medium"],

    # --- Verify Text Message Search ---
    ["AS_026", "Positive", "Verify Text Message Search", "User is logged in and has text messages",
     "Verify text search returns matching messages",
     "1. Open advanced search.\n2. Select 'Text Message' filter.\n3. Type a keyword.",
     "Messages containing the keyword should display in results.",
     "High / High"],
    ["AS_027", "", "", "",
     "Verify text search is case-insensitive",
     "1. Search for 'Hello'.\n2. Search for 'hello'.",
     "Both searches should return the same results.",
     "Medium / Medium"],
    ["AS_028", "", "", "",
     "Verify text search highlights matching text",
     "1. Search for a keyword.\n2. Observe results.",
     "Matching keyword should be highlighted in the search results.",
     "Medium / Low"],
    ["AS_029", "", "", "",
     "Verify partial text search",
     "1. Search for partial word (e.g., 'hel' for 'hello').",
     "Messages containing words starting with or containing the partial text should display.",
     "Medium / Medium"],
    ["AS_030", "", "", "",
     "Verify tapping text result opens conversation",
     "1. Search for a keyword.\n2. Tap on a result.",
     "Should navigate to the conversation and highlight/scroll to the matching message.",
     "High / High"],
    ["AS_031", "Negative", "Verify Text Message Search", "User is logged in",
     "Verify no results for non-matching search",
     "1. Open advanced search.\n2. Search for a random string that doesn't exist.",
     "Empty state should display (e.g., 'No results found').",
     "Medium / Medium"],
    ["AS_032", "", "", "",
     "Verify search with special characters",
     "1. Search for special characters (e.g., '@#$%').",
     "Search should handle special characters gracefully without errors.",
     "Low / Medium"],

    # --- General Advanced Search ---
    ["AS_033", "Positive", "Verify Advanced Search General", "User is logged in",
     "Verify switching between search filters",
     "1. Open advanced search.\n2. Select 'Photos'.\n3. Switch to 'Videos'.\n4. Switch to 'Documents'.",
     "Results should update correctly when switching between filters.",
     "High / High"],
    ["AS_034", "", "", "",
     "Verify search results pagination/infinite scroll",
     "1. Open advanced search with many results.\n2. Scroll down.",
     "More results should load as user scrolls. Loading indicator should appear.",
     "Medium / Medium"],
    ["AS_035", "Negative", "Verify Advanced Search General", "User is logged in, network disconnected",
     "Verify advanced search fails gracefully without network",
     "1. Disconnect network.\n2. Open advanced search.\n3. Try to search.",
     "Appropriate error message should display indicating network issue.",
     "High / High"],
]


# ============================================================
# 3. CONVERSATION SEARCH TEST CASES
# ============================================================
conversation_search_data = [
    # --- Verify Conversation Search UI ---
    ["CS_001", "Positive", "Verify Conversation Search UI", "User is logged in and on Chats tab",
     "Verify search bar is visible on Chats tab",
     "1. Navigate to Chats tab.\n2. Observe top of conversation list.",
     "Search bar/input field should be visible at the top of the conversation list.",
     "High / High"],
    ["CS_002", "", "", "",
     "Verify search bar placeholder text",
     "1. Observe search bar without typing.",
     "Placeholder text should display (e.g., 'Search conversations...').",
     "Low / Low"],
    ["CS_003", "", "", "",
     "Verify search bar activates on tap",
     "1. Tap on search bar.",
     "Search bar should become active with cursor. Keyboard should appear (mobile).",
     "High / High"],
    ["CS_004", "", "", "",
     "Verify clear search input",
     "1. Type text in search bar.\n2. Click clear (X) button.",
     "Search text should clear and full conversation list should restore.",
     "Medium / Medium"],
    ["CS_005", "", "", "",
     "Verify cancel/close search",
     "1. Activate search bar.\n2. Click cancel or press back.",
     "Search should close and return to normal conversation list view.",
     "Medium / Medium"],

    # --- Verify Text Message Search in Conversations ---
    ["CS_006", "Positive", "Verify Text Message Search", "User is logged in with existing conversations",
     "Verify searching by contact/group name",
     "1. Type a contact or group name in search bar.",
     "Matching conversations should filter and display in results.",
     "High / High"],
    ["CS_007", "", "", "",
     "Verify searching by message content",
     "1. Type a keyword from a message in search bar.",
     "Conversations containing messages with that keyword should display.",
     "High / High"],
    ["CS_008", "", "", "",
     "Verify search is case-insensitive",
     "1. Search for 'John'.\n2. Search for 'john'.",
     "Both searches should return the same results.",
     "Medium / Medium"],
    ["CS_009", "", "", "",
     "Verify real-time search results",
     "1. Start typing in search bar character by character.",
     "Results should filter in real-time as user types.",
     "High / Medium"],
    ["CS_010", "", "", "",
     "Verify tapping search result opens conversation",
     "1. Search for a conversation.\n2. Tap on a result.",
     "Should open the matching conversation with message history.",
     "High / High"],
    ["CS_011", "Negative", "Verify Text Message Search", "User is logged in",
     "Verify no results for non-matching search",
     "1. Type a random string that doesn't match any conversation or message.",
     "Empty state should display (e.g., 'No results found').",
     "Medium / Medium"],

    # --- Verify Links Search in Conversations ---
    ["CS_012", "Positive", "Verify Links Search", "User is logged in and has messages with links",
     "Verify links filter in conversation search",
     "1. Open conversation search.\n2. Select 'Links' filter.",
     "Conversations containing link messages should display.",
     "High / High"],
    ["CS_013", "", "", "",
     "Verify link results show URL preview",
     "1. Filter by Links.\n2. Observe results.",
     "Results should show link URL, preview title, sender, and conversation name.",
     "Medium / Medium"],
    ["CS_014", "Negative", "Verify Links Search", "User is logged in with no link messages",
     "Verify empty state for links filter",
     "1. Select 'Links' filter.",
     "Empty state should display indicating no links found.",
     "Medium / Medium"],

    # --- Verify Audio Search in Conversations ---
    ["CS_015", "Positive", "Verify Audio Search", "User is logged in and has audio messages",
     "Verify audio filter in conversation search",
     "1. Open conversation search.\n2. Select 'Audio' filter.",
     "Conversations containing audio messages should display.",
     "High / High"],
    ["CS_016", "", "", "",
     "Verify audio results show details",
     "1. Filter by Audio.\n2. Observe results.",
     "Results should show audio duration, sender, conversation name, and date.",
     "Medium / Medium"],
    ["CS_017", "Negative", "Verify Audio Search", "User is logged in with no audio messages",
     "Verify empty state for audio filter",
     "1. Select 'Audio' filter.",
     "Empty state should display indicating no audio messages found.",
     "Medium / Medium"],

    # --- Verify Documents Search in Conversations ---
    ["CS_018", "Positive", "Verify Documents Search", "User is logged in and has document messages",
     "Verify documents filter in conversation search",
     "1. Open conversation search.\n2. Select 'Documents' filter.",
     "Conversations containing document messages should display.",
     "High / High"],
    ["CS_019", "", "", "",
     "Verify document results show file info",
     "1. Filter by Documents.\n2. Observe results.",
     "Results should show file name, type, size, sender, and date.",
     "Medium / Medium"],
    ["CS_020", "Negative", "Verify Documents Search", "User is logged in with no document messages",
     "Verify empty state for documents filter",
     "1. Select 'Documents' filter.",
     "Empty state should display indicating no documents found.",
     "Medium / Medium"],

    # --- Verify Groups Search ---
    ["CS_021", "Positive", "Verify Groups Search", "User is logged in and is part of groups",
     "Verify groups filter in conversation search",
     "1. Open conversation search.\n2. Select 'Groups' filter.",
     "Only group conversations should display in results.",
     "High / High"],
    ["CS_022", "", "", "",
     "Verify searching within groups filter",
     "1. Select 'Groups' filter.\n2. Type a group name.",
     "Matching group conversations should filter and display.",
     "High / High"],
    ["CS_023", "Negative", "Verify Groups Search", "User is logged in with no group conversations",
     "Verify empty state for groups filter",
     "1. Select 'Groups' filter.",
     "Empty state should display indicating no groups found.",
     "Medium / Medium"],

    # --- Verify Photos Search in Conversations ---
    ["CS_024", "Positive", "Verify Photos Search", "User is logged in and has image messages",
     "Verify photos filter in conversation search",
     "1. Open conversation search.\n2. Select 'Photos' filter.",
     "Conversations containing image messages should display.",
     "High / High"],
    ["CS_025", "", "", "",
     "Verify photo results show thumbnails",
     "1. Filter by Photos.\n2. Observe results.",
     "Results should show image thumbnails, sender, conversation name, and date.",
     "Medium / Medium"],
    ["CS_026", "Negative", "Verify Photos Search", "User is logged in with no image messages",
     "Verify empty state for photos filter",
     "1. Select 'Photos' filter.",
     "Empty state should display indicating no photos found.",
     "Medium / Medium"],

    # --- Verify Videos Search in Conversations ---
    ["CS_027", "Positive", "Verify Videos Search", "User is logged in and has video messages",
     "Verify videos filter in conversation search",
     "1. Open conversation search.\n2. Select 'Videos' filter.",
     "Conversations containing video messages should display.",
     "High / High"],
    ["CS_028", "", "", "",
     "Verify video results show thumbnails",
     "1. Filter by Videos.\n2. Observe results.",
     "Results should show video thumbnails with play icon, duration, sender, and date.",
     "Medium / Medium"],
    ["CS_029", "Negative", "Verify Videos Search", "User is logged in with no video messages",
     "Verify empty state for videos filter",
     "1. Select 'Videos' filter.",
     "Empty state should display indicating no videos found.",
     "Medium / Medium"],

    # --- Verify Unread Search ---
    ["CS_030", "Positive", "Verify Unread Filter", "User is logged in and has unread conversations",
     "Verify unread filter shows unread conversations",
     "1. Open conversation search.\n2. Select 'Unread' filter.",
     "Only conversations with unread messages should display.",
     "High / High"],
    ["CS_031", "", "", "",
     "Verify unread count displayed in results",
     "1. Filter by Unread.\n2. Observe results.",
     "Each conversation should show the unread message count badge.",
     "High / Medium"],
    ["CS_032", "", "", "",
     "Verify conversation removed from unread after reading",
     "1. Filter by Unread.\n2. Open and read a conversation.\n3. Go back to unread filter.",
     "Read conversation should no longer appear in unread filter results.",
     "High / High"],
    ["CS_033", "Negative", "Verify Unread Filter", "User is logged in with all conversations read",
     "Verify empty state for unread filter",
     "1. Select 'Unread' filter.",
     "Empty state should display indicating no unread conversations.",
     "Medium / Medium"],

    # --- General Conversation Search ---
    ["CS_034", "Positive", "Verify Conversation Search General", "User is logged in",
     "Verify switching between search filters",
     "1. Select 'Photos' filter.\n2. Switch to 'Videos'.\n3. Switch to 'Unread'.",
     "Results should update correctly when switching between filters.",
     "High / High"],
    ["CS_035", "", "", "",
     "Verify search results count",
     "1. Perform a search.\n2. Observe result count.",
     "Number of matching results should display.",
     "Low / Low"],
    ["CS_036", "Negative", "Verify Conversation Search General", "User is logged in, network disconnected",
     "Verify search fails gracefully without network",
     "1. Disconnect network.\n2. Try to search.",
     "Appropriate error message should display or cached results should show.",
     "High / High"],
    ["CS_037", "", "", "",
     "Verify search with special characters",
     "1. Type special characters in search bar (e.g., '@#$%&').",
     "Search should handle gracefully without crash or error.",
     "Low / Medium"],
]


# ============================================================
# 4. SEND THREADED MESSAGE TEST CASES
# ============================================================
send_threaded_message_data = [
    # --- Verify Thread UI ---
    ["STM_001", "Positive", "Verify Thread Panel UI", "User is logged in and chat is open",
     "Verify thread panel opens from message menu",
     "1. Long press or hover on a message.\n2. Select 'Reply In Thread'.",
     "Thread panel should open showing the parent message at the top.",
     "High / High"],
    ["STM_002", "", "", "",
     "Verify thread panel shows parent message",
     "1. Open a thread on any message.",
     "Parent message should display at the top of the thread panel with sender info and timestamp.",
     "High / High"],
    ["STM_003", "", "", "",
     "Verify thread composer input field",
     "1. Open a thread panel.\n2. Observe bottom of thread panel.",
     "Message input field should be visible at the bottom of the thread panel.",
     "High / High"],
    ["STM_004", "", "", "",
     "Verify thread panel close button",
     "1. Open a thread panel.\n2. Click close/back button.",
     "Thread panel should close and return to main chat view.",
     "Medium / Medium"],
    ["STM_005", "", "", "",
     "Verify thread reply count on parent message",
     "1. Open a thread and send replies.\n2. Close thread and observe parent message.",
     "Parent message should show reply count (e.g., '3 Replies') in main chat.",
     "High / High"],

    # --- Verify Send Text Message in Thread ---
    ["STM_006", "Positive", "Verify Send Text Message in Thread", "User is logged in and thread is open",
     "Verify sending text message in thread",
     "1. Open a thread.\n2. Type a text message.\n3. Click send.",
     "Text message should appear in the thread below the parent message with timestamp.",
     "High / High"],
    ["STM_007", "", "", "",
     "Verify Enter key sends message in thread",
     "1. Open a thread.\n2. Type a message.\n3. Press Enter.",
     "Message should be sent in the thread.",
     "High / High"],
    ["STM_008", "", "", "",
     "Verify multiple text messages in thread",
     "1. Send multiple text messages in a thread.",
     "All messages should display in chronological order within the thread.",
     "High / High"],
    ["STM_009", "", "", "",
     "Verify thread message shows sender info",
     "1. Have multiple users reply in a thread.\n2. Observe messages.",
     "Each message should show sender name, avatar, and timestamp.",
     "High / Medium"],
    ["STM_010", "", "", "",
     "Verify long text message in thread",
     "1. Type a very long text message in thread.\n2. Send.",
     "Long message should display properly with text wrapping. No truncation.",
     "Medium / Medium"],
    ["STM_011", "", "", "",
     "Verify emoji message in thread",
     "1. Send an emoji-only message in thread.",
     "Emoji should display in larger size in the thread.",
     "Low / Low"],
    ["STM_012", "Negative", "Verify Send Text Message in Thread", "User is logged in and thread is open",
     "Verify empty message not sent in thread",
     "1. Open a thread.\n2. Leave input empty.\n3. Click send.",
     "Empty message should not be sent. Send button should be disabled or no action.",
     "High / High"],
    ["STM_013", "", "", "User is logged in, network disconnected",
     "Verify text message fails in thread without network",
     "1. Disconnect network.\n2. Try to send text message in thread.",
     "Error message should display or message should queue with retry option.",
     "High / High"],

    # --- Verify Send Media in Thread ---
    ["STM_014", "Positive", "Verify Send Media in Thread", "User is logged in and thread is open",
     "Verify attach button available in thread composer",
     "1. Open a thread.\n2. Observe thread composer.",
     "Attach/attachment button should be available in the thread input area.",
     "High / High"],
    ["STM_015", "", "", "",
     "Verify sending image in thread",
     "1. Open a thread.\n2. Click attach.\n3. Select an image.\n4. Send.",
     "Image should upload and display in the thread with thumbnail.",
     "High / High"],
    ["STM_016", "", "", "",
     "Verify sending video in thread",
     "1. Open a thread.\n2. Click attach.\n3. Select a video.\n4. Send.",
     "Video should upload and display in the thread with thumbnail and play icon.",
     "High / High"],
    ["STM_017", "", "", "",
     "Verify sending audio in thread",
     "1. Open a thread.\n2. Click attach or record.\n3. Select/record audio.\n4. Send.",
     "Audio message should display in thread with play button and duration.",
     "High / High"],
    ["STM_018", "", "", "",
     "Verify sending document in thread",
     "1. Open a thread.\n2. Click attach.\n3. Select a document.\n4. Send.",
     "Document should upload and display with file icon, name, and size in thread.",
     "High / High"],
    ["STM_019", "", "", "",
     "Verify image preview in thread",
     "1. Send an image in thread.\n2. Tap on the image thumbnail.",
     "Full-size image preview should open.",
     "Medium / Medium"],
    ["STM_020", "", "", "",
     "Verify video playback in thread",
     "1. Send a video in thread.\n2. Tap play on the video.",
     "Video should play within the thread or in a media player.",
     "Medium / Medium"],
    ["STM_021", "Negative", "Verify Send Media in Thread", "User is logged in and thread is open",
     "Verify file size limit in thread",
     "1. Open a thread.\n2. Try to attach a file exceeding size limit.",
     "Error message should display indicating file size limit exceeded.",
     "High / Medium"],
    ["STM_022", "", "", "User is logged in, network disconnected",
     "Verify media upload fails in thread without network",
     "1. Disconnect network.\n2. Try to send media in thread.",
     "Error message should display or upload should queue with retry option.",
     "High / High"],
    ["STM_023", "", "", "User is logged in and thread is open",
     "Verify unsupported file type in thread",
     "1. Try to attach an unsupported file type in thread.",
     "Error message should display or file type should be rejected.",
     "Medium / Medium"],

    # --- Verify Send Custom Message in Thread ---
    ["STM_024", "Positive", "Verify Send Custom Message in Thread", "User is logged in and thread is open",
     "Verify sending sticker in thread",
     "1. Open a thread.\n2. Open sticker picker.\n3. Select a sticker.",
     "Sticker should be sent and display in the thread.",
     "Medium / Medium"],
    ["STM_025", "", "", "",
     "Verify sending GIF in thread",
     "1. Open a thread.\n2. Open GIF picker.\n3. Select a GIF.",
     "GIF should be sent and display/animate in the thread.",
     "Medium / Medium"],
    ["STM_026", "", "", "",
     "Verify sending location in thread (if supported)",
     "1. Open a thread.\n2. Share location.",
     "Location message with map preview should display in the thread.",
     "Low / Low"],

    # --- Verify Thread Notifications ---
    ["STM_027", "Positive", "Verify Thread Notifications", "User is logged in and has participated in a thread",
     "Verify notification for new thread reply",
     "1. Another user replies in a thread you participated in.\n2. Observe notifications.",
     "Notification should appear for the new thread reply.",
     "High / High"],
    ["STM_028", "", "", "",
     "Verify thread reply count updates in real-time",
     "1. Be on main chat.\n2. Another user replies in a thread.",
     "Reply count on parent message should update in real-time.",
     "High / Medium"],

    # --- Verify Thread Message Actions ---
    ["STM_029", "Positive", "Verify Thread Message Actions", "User is logged in and thread is open",
     "Verify copy message in thread",
     "1. Long press on a text message in thread.\n2. Select 'Copy'.",
     "Message text should be copied to clipboard.",
     "Medium / Medium"],
    ["STM_030", "", "", "",
     "Verify delete own message in thread",
     "1. Long press on own message in thread.\n2. Select 'Delete'.\n3. Confirm.",
     "Message should be deleted from the thread. Reply count should update.",
     "High / High"],
    ["STM_031", "", "", "",
     "Verify edit own message in thread",
     "1. Long press on own text message in thread.\n2. Select 'Edit'.\n3. Modify and save.",
     "Message should update with new text and show 'edited' indicator.",
     "High / High"],
    ["STM_032", "", "", "",
     "Verify react to message in thread",
     "1. Long press on a message in thread.\n2. Select a reaction.",
     "Reaction should appear below the message in the thread.",
     "Medium / Medium"],
    ["STM_033", "Negative", "Verify Thread Message Actions", "User is logged in and thread is open",
     "Verify cannot edit others' messages in thread",
     "1. Long press on another user's message in thread.\n2. Observe menu.",
     "'Edit' option should NOT be available for other users' messages.",
     "High / High"],
    ["STM_034", "", "", "",
     "Verify cannot delete others' messages in thread",
     "1. Long press on another user's message in thread.\n2. Observe menu.",
     "'Delete' option should NOT be available for other users' messages (unless admin).",
     "High / High"],

    # --- Verify Thread in Group vs One-on-One ---
    ["STM_035", "Positive", "Verify Thread in One-on-One Chat", "User is logged in and one-on-one chat is open",
     "Verify thread works in one-on-one conversation",
     "1. Open a one-on-one chat.\n2. Reply in thread on a message.\n3. Send a reply.",
     "Thread should work correctly in one-on-one conversations.",
     "High / High"],
    ["STM_036", "", "Verify Thread in Group Chat", "User is logged in and group chat is open",
     "Verify thread works in group conversation",
     "1. Open a group chat.\n2. Reply in thread on a message.\n3. Send a reply.",
     "Thread should work correctly in group conversations with multiple participants.",
     "High / High"],
    ["STM_037", "", "", "",
     "Verify multiple users can reply in same thread",
     "1. Have 3+ users reply in the same thread.",
     "All replies should display correctly with respective sender info.",
     "High / High"],
    ["STM_038", "", "", "",
     "Verify thread scroll with many replies",
     "1. Open a thread with 50+ replies.\n2. Scroll through.",
     "All replies should load and scroll smoothly. Older replies should load on scroll up.",
     "Medium / Medium"],
]


# ============================================================
# CREATE ALL EXCEL FILES
# ============================================================

create_workbook(
    "Message List Test Cases", headers, message_list_data,
    "cometchat-test-cases/Message_List/Message_List_Test_Cases.xlsx"
)

create_workbook(
    "Advanced Search Test Cases", headers, advanced_search_data,
    "cometchat-test-cases/Advanced_Search/Advanced_Search_Test_Cases.xlsx"
)

create_workbook(
    "Conversation Search Test Cases", headers, conversation_search_data,
    "cometchat-test-cases/Conversation_Search/Conversation_Search_Test_Cases.xlsx"
)

create_workbook(
    "Threaded Message Test Cases", headers, send_threaded_message_data,
    "cometchat-test-cases/Send_Threaded_Message/Send_Threaded_Message_Test_Cases.xlsx"
)

print("\nAll test case files generated successfully!")
